/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ak. Generated by core-i18n. */
export default {
  close: "Tum",
  error_dialogs: {
    cancel_btn: "Gyae anim mfoninitwa no",
    check_internet_connection: {
      aria_description: "Fa wo ho hyɛ intanɛt so, na san bɔ mmɔden sɛ wobɛtwa anim mfonini.",
      title: "Hwɛ wo intanɛt nkitahodi no",
    },
    network_error: {
      aria_description: "San bɔ mmɔden sɛ wobɛtwa anim mfonini. Sɛ ɔhaw no kɔ so a, gyae na san bɔ mmɔden akyiri yi.",
      title: "Nkitahodi mfomso",
    },
    retry_btn: "San yɛ bio",
    scanning_not_available: {
      aria_description: "To nkɔmmɔ adaka yi mu na san bɔ mmɔden akyiri yi.",
      title: "Anim mfoninitwa nni hɔ",
    },
    scanning_unsuccessful: {
      details: "Yentumi nhu w'anim. Yɛsrɛ wo, san bɔ mmɔden.",
      title: "Anim mfoninitwa anyɛ yiye",
    },
  },
  feedback_messages: {
    angled_pitch: "Hwɛ kamera no mu tee",
    angled_roll: "Hwɛ kamera no mu tee",
    angled_yaw: "Hwɛ kamera no mu tee",
    capture_complete_aria: "Ayɛ yiye! Wɔatwa w'anim ho mfonini",
    face_not_found: "Fa w'anim hyɛ skreen no mfinimfini",
    multiple_faces: "Ɛsɛ sɛ anim baako pɛ na ɛda adi",
    not_still: "Mma wo ho nhinhim",
    ok: "Ɛyɛ pɛ! Mma wo ho nhinhim",
    too_blurry: "Mma wo ho nhinhim",
    too_bright: "Kɔ baabi a hann no nyɛ den pii",
    too_close: "Kɔ akyirikyiri",
    too_close_to_border: "Fa w'anim hyɛ mfinimfini",
    too_dark: "Kɔ baabi a hann wɔ hɔ pii",
    too_far: "Bɛn ho",
  },
  help_button: {
    aria_label: "Mmoa",
    tooltip: "Wohia mmoa?",
  },
  help_modal: {
    aria: "Anim mfoninitwa ho mmoa",
    back_btn: "Akyire",
    done_btn: "Awiei",
    done_btn_aria: "Toa anim mfonini kyere no so",
    next_btn: "Nea Edi Hɔ",
    steps: {
      camera_lens: {
        details: "Hwɛ sɛ nkekae anaa mfutuma nni wo kamera ahwehwɛ no so. Kamera ahwehwɛ a ɛho ntew betumi ama wo mfonini ayɛ kusuu na ama ayɛ den sɛ nhyehyɛe no bɛtwa w'anim ho mfonini pefee.",
        title: "Popa wo kamɛra lɛns",
      },
      centered_face: {
        details: "Hwɛ kamera no tẽẽ na fa w'anim hyɛ skreen no mfinimfini. Kura wo afiri no pintinn na ma w'anim nyɛ sɛnea ɛte daa kosi sɛ wɔbɛtwa w'anim ho mfonini.",
        title: "Ma w'anim ntra mfinimfini",
      },
      lighting: {
        details: "Hwɛ sɛ wohu w'anim pefee. Kwati baabi a esum dodo anaa hann dɔɔso, na fa w'anim kyerɛ hann fibea no sen sɛ hann no bɛfi w'akyi.",
        title: "Hwehwɛ hann pa",
      },
      obstructions: {
        details: "Hwɛ sɛ biribiara nkata w'anim so. Yi aniwa ahwehwɛ a ɛbɔ owia ano, kyɛw, anaa biribiara a esiw w'ani anaa w'anim ho afã ahorow.",
        title: "Yi nneɛma a ɛkata so no",
      },
    },
  },
  onboarding_modal: {
    aria: "Akwankyerɛ a ɛfa anim mfonini kyere ho",
    cancel_btn: "Twa mu",
    details: "Hwɛ hu sɛ worenkeka wo ho, na fa w’anim hyɛ kamera no mfinimfini.",
    start_btn: "Fi ase skaane",
    title: "Hwɛ kamera no mu tee",
  },
  processing: "Wɔreyɛ ho adwuma...",
  sdk_aria: "Kyere w’anim mfonini",
} as const;
