/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for am. Generated by core-i18n. */
export default {
  close: "ዝጋ",
  error_dialogs: {
    cancel_btn: "መቃኘትን ይሰርዙ",
    check_internet_connection: {
      aria_description: "ከበይነመረብ ጋር ይገናኙ፣ ከዚያ መቃኘቱን እንደገና ይሞክሩ።",
      title: "የበይነመረብ ግንኙነቱን ያረጋግጡ",
    },
    network_error: {
      aria_description: "መቃኘቱን እንደገና ይሞክሩ። ችግሩ ከቀጠለ፣ ይሰርዙ እና በኋላ እንደገና ይሞክሩ።",
      title: "የአውታረ መረብ ስህተት",
    },
    retry_btn: "እንደገና ይሞክሩ",
    scanning_not_available: {
      aria_description: "ይህን መገናኛ ሳጥን ይዝጉ እና በኋላ እንደገና ይሞክሩ።",
      title: "መቃኘት አይገኝም",
    },
    scanning_unsuccessful: {
      details: "ፊትዎን መለየት አልተቻለም። እባክዎ እንደገና ይሞክሩ።",
      title: "መቃኘቱ አልተሳካም",
    },
  },
  feedback_messages: {
    angled_pitch: "ወደ ካሜራው ቀጥ ብለው ይመልከቱ",
    angled_roll: "ወደ ካሜራው ቀጥ ብለው ይመልከቱ",
    angled_yaw: "ወደ ካሜራው ቀጥ ብለው ይመልከቱ",
    capture_complete_aria: "ተሳክቷል! ፊትዎ ተቀርጿል",
    face_not_found: "ፊትዎን በማያ ገጹ መሃል ያድርጉ",
    multiple_faces: "አንድ ፊት ብቻ መታየት አለበት",
    not_still: "ሳይንቀሳቀሱ ይቆዩ",
    ok: "በጣም ጥሩ! ሳይንቀሳቀሱ ይቆዩ",
    too_blurry: "ሳይንቀሳቀሱ ይቆዩ",
    too_bright: "ለስላሳ ብርሃን ወዳለበት ቦታ ይሂዱ",
    too_close: "ራቅ ብለው ይሂዱ",
    too_close_to_border: "ፊትዎን መሃል ያድርጉ",
    too_dark: "ወደ ብሩህ ቦታ ይሂዱ",
    too_far: "ይቅረቡ",
  },
  help_button: {
    aria_label: "እገዛ",
    tooltip: "እርዳታ ይፈልጋሉ?",
  },
  help_modal: {
    aria: "የፊት ቀረጻ እገዛ",
    back_btn: "ተመለስ",
    done_btn: "ተከናውኗል",
    done_btn_aria: "የፊት ቀረጻውን ይቀጥሉ",
    next_btn: "ቀጣይ",
    steps: {
      camera_lens: {
        details: "የካሜራ ሌንስዎ ላይ እድፍ ወይም አቧራ እንዳለ ያረጋግጡ። የቆሸሸ ሌንስ ፎቶዎን ሊያደበዝዝ እና ስርዓቱ ፊትዎን በግልጽ እንዲቀርጽ ሊያስቸግረው ይችላል።",
        title: "የካሜራዎን ሌንሶች ያጽዱ",
      },
      centered_face: {
        details: "ወደ ካሜራው ቀጥ ብለው ይመልከቱ እና ፊትዎን በማያ ገጹ መሃል ያድርጉ። መሣሪያዎን በተረጋጋ ሁኔታ ይያዙ እና ፊትዎ እስኪቀረጽ ድረስ ገለልተኛ የፊት ገጽታ ይያዙ።",
        title: "ፊትዎን መሃል ላይ ያቆዩ",
      },
      lighting: {
        details: "ፊትዎ በግልጽ እንደሚታይ ያረጋግጡ። በጣም ጨለማ ወይም በጣም ብሩህ ብርሃንን ያስወግዱ፣ እንዲሁም ብርሃኑ ከኋላዎ እንዳይሆን ወደ ብርሃን ምንጩ ይመልከቱ።",
        title: "ጥሩ ብርሃን ያግኙ",
      },
      obstructions: {
        details: "ምንም ነገር ፊትዎን እንዳልሸፈነ ያረጋግጡ። ዓይንዎን ወይም የፊትዎን ገጽታዎች የሚያግዱ የፀሐይ መነጽሮችን፣ ኮፍያዎችን ወይም ሌሎች ነገሮችን ያስወግዱ።",
        title: "መሸፈኛዎችን ያስወግዱ",
      },
    },
  },
  onboarding_modal: {
    aria: "የፊት ቀረጻ መመሪያዎች",
    cancel_btn: "ሰርዝ",
    details: "ሳይንቀሳቀሱ ይቆዩ እና ፊትዎን በካሜራው ማያ ገጽ መሃል ያድርጉ።",
    start_btn: "መቃኘት ጀምር",
    title: "ወደ ካሜራው ቀጥ ብለው ይመልከቱ",
  },
  processing: "በማስኬድ ላይ...",
  sdk_aria: "ፊትዎን ይቅረጹ",
} as const;
