/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ar. Generated by core-i18n. */
export default {
  close: "إغلاق",
  error_dialogs: {
    cancel_btn: "إلغاء المسح",
    check_internet_connection: {
      aria_description: "اتصل بالإنترنت، ثم أعد محاولة المسح.",
      title: "تحقق من الاتصال بالإنترنت",
    },
    network_error: {
      aria_description: "أعد محاولة المسح. إذا استمرت المشكلة، فألغِ العملية وحاول مرة أخرى لاحقًا.",
      title: "خطأ في الشبكة",
    },
    retry_btn: "إعادة المحاولة",
    scanning_not_available: {
      aria_description: "أغلق مربع الحوار هذا وحاول مرة أخرى لاحقًا.",
      title: "المسح غير متاح",
    },
    scanning_unsuccessful: {
      details: "تعذر اكتشاف وجهك. يُرجى المحاولة مرة أخرى.",
      title: "لم ينجح المسح",
    },
  },
  feedback_messages: {
    angled_pitch: "انظر مباشرةً إلى الكاميرا",
    angled_roll: "انظر مباشرةً إلى الكاميرا",
    angled_yaw: "انظر مباشرةً إلى الكاميرا",
    capture_complete_aria: "نجاح! تم التقاط الوجه",
    face_not_found: "ضع وجهك في وسط الشاشة",
    multiple_faces: "تأكد من ظهور وجه واحد فقط",
    not_still: "ابقَ ثابتًا",
    ok: "ممتاز! ابقَ ثابتًا",
    too_blurry: "ابقَ ثابتًا",
    too_bright: "انتقل إلى مكان بإضاءة أكثر نعومة",
    too_close: "انقل إلى موضع أبعد",
    too_close_to_border: "ضع وجهك في الوسط",
    too_dark: "انتقل إلى مكان أكثر إضاءة",
    too_far: "انقل إلى موضع أقرب",
  },
  help_button: {
    aria_label: "المساعدة",
    tooltip: "هل تحتاج مساعدة؟",
  },
  help_modal: {
    aria: "المساعدة في التقاط الوجه",
    back_btn: "عودة",
    done_btn: "انتهى",
    done_btn_aria: "استئناف التقاط الوجه",
    next_btn: "التالي",
    steps: {
      camera_lens: {
        details: "تحقق من عدم وجود لطخات أو غبار على عدسة الكاميرا. قد تؤدي العدسة المتسخة إلى تشويش صورتك وتجعل من الصعب على النظام التقاط وجهك بوضوح.",
        title: "يرجى تنظيف عدسة الكاميرا",
      },
      centered_face: {
        details: "انظر مباشرةً إلى الكاميرا وضع وجهك في وسط الشاشة. أمسك جهازك بثبات وحافظ على تعبير محايد حتى يتم التقاط وجهك.",
        title: "أبقِ وجهك في الوسط",
      },
      lighting: {
        details: "تأكد من أن وجهك ظاهر بوضوح. تجنب الإضاءة الخافتة جدًا أو الساطعة جدًا، واجعل مصدر الضوء أمامك بدلًا من أن يكون خلفك.",
        title: "ابحث عن إضاءة جيدة",
      },
      obstructions: {
        details: "تأكد من عدم وجود ما يغطي وجهك. أزل النظارات الشمسية أو القبعات أو أي شيء يحجب عينيك أو ملامح وجهك.",
        title: "أزل العوائق",
      },
    },
  },
  onboarding_modal: {
    aria: "تعليمات التقاط الوجه",
    cancel_btn: "إلغاء",
    details: "حافظ على ثباتك ووسّط وجهك في إطار الكاميرا.",
    start_btn: "بدء المسح",
    title: "انظر مباشرةً إلى الكاميرا",
  },
  processing: "تجري المعالجة...",
  sdk_aria: "التقط وجهك",
} as const;
