/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for cs. Generated by core-i18n. */
export default {
  close: "Zavřít",
  error_dialogs: {
    cancel_btn: "Zrušit skenování",
    check_internet_connection: {
      aria_description: "Připojte se k internetu a poté skenování opakujte.",
      title: "Zkontrolujte připojení k internetu",
    },
    network_error: {
      aria_description: "Opakujte skenování. Pokud problém přetrvává, zrušte skenování a zkuste to později.",
      title: "Chyba sítě",
    },
    retry_btn: "Opakovat",
    scanning_not_available: {
      aria_description: "Zavřete toto dialogové okno a zkuste to později.",
      title: "Skenování není k dispozici",
    },
    scanning_unsuccessful: {
      details: "Obličej se nepodařilo najít. Zkuste to znovu.",
      title: "Skenování se nezdařilo",
    },
  },
  feedback_messages: {
    angled_pitch: "Dívejte se přímo do fotoaparátu",
    angled_roll: "Dívejte se přímo do fotoaparátu",
    angled_yaw: "Dívejte se přímo do fotoaparátu",
    capture_complete_aria: "Obličej byl úspěšně zachycen",
    face_not_found: "Umístěte obličej doprostřed obrazovky",
    multiple_faces: "Viditelný by měl být pouze jeden obličej",
    not_still: "Nehýbejte se",
    ok: "Výborně! Nehýbejte se",
    too_blurry: "Nehýbejte se",
    too_bright: "Přejděte na místo s mírnějším osvětlením",
    too_close: "Kousek dál",
    too_close_to_border: "Umístěte obličej doprostřed",
    too_dark: "Přejděte na světlejší místo",
    too_far: "Kousek blíž",
  },
  help_button: {
    aria_label: "Nápověda",
    tooltip: "Potřebujete pomoct?",
  },
  help_modal: {
    aria: "Nápověda k zachycení obličeje",
    back_btn: "Zpět",
    done_btn: "Hotovo",
    done_btn_aria: "Pokračovat v pořizování snímku obličeje",
    next_btn: "Další",
    steps: {
      camera_lens: {
        details: "Zkontrolujte, zda na objektivu fotoaparátu nejsou šmouhy nebo prach. Znečištěný objektiv může fotografii rozmazat a ztížit systému zřetelné zachycení obličeje.",
        title: "Vyčistěte objektiv fotoaparátu",
      },
      centered_face: {
        details: "Dívejte se přímo do fotoaparátu a umístěte obličej doprostřed obrazovky. Držte zařízení pevně a zachovejte neutrální výraz, dokud nebude obličej zachycen.",
        title: "Udržujte obličej uprostřed",
      },
      lighting: {
        details: "Ujistěte se, že je obličej jasně viditelný. Vyhněte se příliš slabému nebo příliš intenzivnímu osvětlení a buďte čelem ke zdroji světla, ne zády k němu.",
        title: "Zajistěte dobré osvětlení",
      },
      obstructions: {
        details: "Ujistěte se, že obličej nic nezakrývá. Sundejte sluneční brýle, klobouk nebo cokoli, co zakrývá oči či rysy obličeje.",
        title: "Odkryjte si obličej",
      },
    },
  },
  onboarding_modal: {
    aria: "Pokyny k pořízení snímku obličeje",
    cancel_btn: "Zrušit",
    details: "Nehýbejte se a umístěte obličej doprostřed záběru.",
    start_btn: "Spustit skenování",
    title: "Dívejte se přímo do fotoaparátu",
  },
  processing: "Zpracovává se...",
  sdk_aria: "Pořiďte snímek obličeje",
} as const;
