/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for da. Generated by core-i18n. */
export default {
  close: "Luk",
  error_dialogs: {
    cancel_btn: "Annuller scanning",
    check_internet_connection: {
      aria_description: "Opret forbindelse til internettet, og prøv derefter at scanne igen.",
      title: "Kontrollér internetforbindelsen",
    },
    network_error: {
      aria_description: "Prøv at scanne igen. Hvis problemet fortsætter, skal du annullere og prøve igen senere.",
      title: "Netværksfejl",
    },
    retry_btn: "Prøv igen",
    scanning_not_available: {
      aria_description: "Luk denne dialogboks, og prøv igen senere.",
      title: "Scanning er ikke tilgængelig",
    },
    scanning_unsuccessful: {
      details: "Dit ansigt kunne ikke registreres. Prøv igen.",
      title: "Scanning mislykkedes",
    },
  },
  feedback_messages: {
    angled_pitch: "Se direkte ind i kameraet",
    angled_roll: "Se direkte ind i kameraet",
    angled_yaw: "Se direkte ind i kameraet",
    capture_complete_aria: "Ansigtet er registreret",
    face_not_found: "Centrer dit ansigt på skærmen",
    multiple_faces: "Kun ét ansigt må være synligt",
    not_still: "Hold dig i ro",
    ok: "Perfekt! Hold dig i ro",
    too_blurry: "Hold dig i ro",
    too_bright: "Flyt til et sted med blødere belysning",
    too_close: "Flyt længere væk",
    too_close_to_border: "Centrer dit ansigt",
    too_dark: "Flyt til et lysere sted",
    too_far: "Flyt tættere på",
  },
  help_button: {
    aria_label: "Hjælp",
    tooltip: "Brug for hjælp?",
  },
  help_modal: {
    aria: "Hjælp til ansigtsoptagelse",
    back_btn: "Tilbage",
    done_btn: "Færdig",
    done_btn_aria: "Fortsæt ansigtsoptagelsen",
    next_btn: "Næste",
    steps: {
      camera_lens: {
        details: "Kontrollér kameralinsen for pletter eller støv. En snavset linse kan gøre billedet uskarpt og gøre det sværere for systemet at registrere dit ansigt tydeligt.",
        title: "Rens din kameralinse",
      },
      centered_face: {
        details: "Se lige ind i kameraet, og centrer dit ansigt på skærmen. Hold enheden stille, og bevar et neutralt ansigtsudtryk, indtil dit ansigt er registreret.",
        title: "Hold dit ansigt centreret",
      },
      lighting: {
        details: "Sørg for, at dit ansigt er tydeligt synligt. Undgå meget mørk eller meget kraftig belysning, og vend ansigtet mod lyskilden i stedet for at have den bag dig.",
        title: "Find god belysning",
      },
      obstructions: {
        details: "Sørg for, at intet dækker dit ansigt. Tag solbriller, hat eller andet af, som dækker dine øjne eller ansigtstræk.",
        title: "Fjern genstande, der dækker ansigtet",
      },
    },
  },
  onboarding_modal: {
    aria: "Instruktioner til ansigtsoptagelse",
    cancel_btn: "Annuller",
    details: "Hold dig stille, og placer dit ansigt midt på skærmen.",
    start_btn: "Start scanning",
    title: "Se direkte ind i kameraet",
  },
  processing: "Behandler...",
  sdk_aria: "Optag dit ansigt",
} as const;
