/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for de. Generated by core-i18n. */
export default {
  close: "Schließen",
  error_dialogs: {
    cancel_btn: "Scanvorgang abbrechen",
    check_internet_connection: {
      aria_description: "Stellen Sie eine Internetverbindung her und versuchen Sie den Scan dann erneut.",
      title: "Internetverbindung überprüfen",
    },
    network_error: {
      aria_description: "Versuchen Sie den Scan erneut. Wenn das Problem weiterhin besteht, brechen Sie ab und versuchen Sie es später erneut.",
      title: "Netzwerkfehler",
    },
    retry_btn: "Wiederholen",
    scanning_not_available: {
      aria_description: "Schließen Sie diesen Dialog und versuchen Sie es später erneut.",
      title: "Scanvorgang nicht verfügbar",
    },
    scanning_unsuccessful: {
      details: "Ihr Gesicht wurde nicht erkannt. Bitte versuchen Sie es erneut.",
      title: "Scanvorgang fehlgeschlagen",
    },
  },
  feedback_messages: {
    angled_pitch: "Schauen Sie gerade in die Kamera",
    angled_roll: "Schauen Sie gerade in die Kamera",
    angled_yaw: "Schauen Sie gerade in die Kamera",
    capture_complete_aria: "Gesicht erfolgreich erfasst.",
    face_not_found: "Positionieren Sie Ihr Gesicht in der Mitte des Bildschirms",
    multiple_faces: "Achten Sie darauf, dass nur ein Gesicht sichtbar ist",
    not_still: "Halten Sie still",
    ok: "Perfekt. Halten Sie still",
    too_blurry: "Halten Sie still",
    too_bright: "Gehen Sie an einen Ort mit weniger grellem Licht",
    too_close: "Bewegen Sie sich weiter weg",
    too_close_to_border: "Positionieren Sie Ihr Gesicht in der Mitte",
    too_dark: "Gehen Sie an einen helleren Ort",
    too_far: "Kommen Sie näher",
  },
  help_button: {
    aria_label: "Hilfe",
    tooltip: "Brauchen Sie Hilfe?",
  },
  help_modal: {
    aria: "Hilfe zur Gesichtserfassung",
    back_btn: "Zurück",
    done_btn: "Fertig",
    done_btn_aria: "Gesichtserfassung fortsetzen",
    next_btn: "Weiter",
    steps: {
      camera_lens: {
        details: "Überprüfen Sie Ihr Kameraobjektiv auf Schlieren oder Staub. Ein verschmutztes Objektiv kann Ihr Bild unscharf machen und es dem System erschweren, Ihr Gesicht deutlich zu erfassen.",
        title: "Reinigen Sie Ihr Kameraobjektiv",
      },
      centered_face: {
        details: "Schauen Sie direkt in die Kamera und positionieren Sie Ihr Gesicht in der Mitte des Bildschirms. Halten Sie Ihr Gerät ruhig und behalten Sie einen neutralen Gesichtsausdruck bei, bis Ihr Gesicht erfasst wurde.",
        title: "Halten Sie Ihr Gesicht mittig",
      },
      lighting: {
        details: "Stellen Sie sicher, dass Ihr Gesicht deutlich sichtbar ist. Vermeiden Sie sehr dunkles oder sehr helles Licht und richten Sie Ihr Gesicht zur Lichtquelle, statt sie hinter sich zu haben.",
        title: "Sorgen Sie für gute Beleuchtung",
      },
      obstructions: {
        details: "Stellen Sie sicher, dass nichts Ihr Gesicht bedeckt. Nehmen Sie Sonnenbrillen, Hüte oder andere Gegenstände ab, die Ihre Augen oder Gesichtszüge verdecken.",
        title: "Entfernen Sie alles, was Ihr Gesicht verdeckt",
      },
    },
  },
  onboarding_modal: {
    aria: "Anweisungen zur Gesichtserfassung",
    cancel_btn: "Abbrechen",
    details: "Halten Sie still und richten Sie Ihr Gesicht mittig im Kamerabild aus.",
    start_btn: "Scannen beginnen",
    title: "Schauen Sie gerade in die Kamera",
  },
  processing: "Wird verarbeitet ...",
  sdk_aria: "Erfassen Sie Ihr Gesicht",
} as const;
