/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for en_GB. Generated by core-i18n. */
export default {
  close: "Close",
  error_dialogs: {
    cancel_btn: "Cancel scanning",
    check_internet_connection: {
      aria_description: "Connect to the internet, then retry scanning.",
      title: "Check internet connection",
    },
    network_error: {
      aria_description: "Retry scanning. If the problem continues, cancel and try again later.",
      title: "Network error",
    },
    retry_btn: "Retry",
    scanning_not_available: {
      aria_description: "Close this dialog and try again later.",
      title: "Scanning not available",
    },
    scanning_unsuccessful: {
      details: "Unable to detect your face. Please try again.",
      title: "Scanning unsuccessful",
    },
  },
  feedback_messages: {
    angled_pitch: "Look straight into the camera",
    angled_roll: "Look straight into the camera",
    angled_yaw: "Look straight into the camera",
    capture_complete_aria: "Success! Face captured",
    face_not_found: "Centre your face on the screen",
    multiple_faces: "Only one face should be visible",
    not_still: "Keep still",
    ok: "Perfect! Stay still",
    too_blurry: "Keep still",
    too_bright: "Move to a spot with softer lighting",
    too_close: "Move farther",
    too_close_to_border: "Centre your face",
    too_dark: "Move to a brighter spot",
    too_far: "Move closer",
  },
  help_button: {
    aria_label: "Help",
    tooltip: "Need help?",
  },
  help_modal: {
    aria: "Face capture help",
    back_btn: "Back",
    done_btn: "Done",
    done_btn_aria: "Resume face capture",
    next_btn: "Next",
    steps: {
      camera_lens: {
        details: "Check your camera lens for smudges or dust. A dirty lens can blur your photo and make it harder for the system to capture your face clearly.",
        title: "Clean your camera lens",
      },
      centered_face: {
        details: "Look straight at the camera and centre your face on the screen. Hold your device steady and keep a neutral expression until your face is captured.",
        title: "Keep your face centred",
      },
      lighting: {
        details: "Make sure your face is clearly visible. Avoid very dark or very bright lighting, and face the light source rather than having it behind you.",
        title: "Find good lighting",
      },
      obstructions: {
        details: "Make sure nothing is covering your face. Remove sunglasses, hats, or anything that blocks your eyes or facial features.",
        title: "Remove obstructions",
      },
    },
  },
  onboarding_modal: {
    aria: "Face capture instructions",
    cancel_btn: "Cancel",
    details: "Keep still and centre your face in the camera view.",
    start_btn: "Start Scanning",
    title: "Look straight into the camera",
  },
  processing: "Processing...",
  sdk_aria: "Capture your face",
} as const;
