/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for es. Generated by core-i18n. */
export default {
  close: "Cerrar",
  error_dialogs: {
    cancel_btn: "Cancelar escaneo",
    check_internet_connection: {
      aria_description: "Conéctate a internet y vuelve a intentar el escaneo.",
      title: "Comprueba la conexión a internet",
    },
    network_error: {
      aria_description: "Vuelve a intentar el escaneo. Si el problema continúa, cancela e inténtalo más tarde.",
      title: "Error de red",
    },
    retry_btn: "Reintentar",
    scanning_not_available: {
      aria_description: "Cierra este cuadro de diálogo e inténtalo más tarde.",
      title: "El escaneo no está disponible",
    },
    scanning_unsuccessful: {
      details: "No se pudo detectar tu rostro. Inténtalo de nuevo.",
      title: "El escaneo no se completó",
    },
  },
  feedback_messages: {
    angled_pitch: "Mira directamente a la cámara",
    angled_roll: "Mira directamente a la cámara",
    angled_yaw: "Mira directamente a la cámara",
    capture_complete_aria: "Rostro capturado correctamente",
    face_not_found: "Centra tu rostro en la pantalla",
    multiple_faces: "Debe verse solo un rostro",
    not_still: "No te muevas",
    ok: "Perfecto. No te muevas",
    too_blurry: "No te muevas",
    too_bright: "Muévete a un lugar con luz más suave",
    too_close: "Alejarse",
    too_close_to_border: "Centra tu rostro",
    too_dark: "Muévete a un lugar más iluminado",
    too_far: "Acercarse",
  },
  help_button: {
    aria_label: "Ayuda",
    tooltip: "¿Necesitas ayuda?",
  },
  help_modal: {
    aria: "Ayuda para la captura del rostro",
    back_btn: "Atrás",
    done_btn: "Hecho",
    done_btn_aria: "Reanudar la captura facial",
    next_btn: "Siguiente",
    steps: {
      camera_lens: {
        details: "Comprueba si la lente de la cámara tiene manchas o polvo. Una lente sucia puede desenfocar la imagen y dificultar que el sistema capture tu rostro con claridad.",
        title: "Limpia la lente de la cámara",
      },
      centered_face: {
        details: "Mira directamente a la cámara y centra tu rostro en la pantalla. Mantén el dispositivo firme y una expresión neutra hasta que se capture tu rostro.",
        title: "Mantén el rostro centrado",
      },
      lighting: {
        details: "Asegúrate de que tu rostro se vea con claridad. Evita una iluminación muy oscura o muy intensa y mira hacia la fuente de luz en lugar de tenerla detrás.",
        title: "Busca buena iluminación",
      },
      obstructions: {
        details: "Asegúrate de que nada cubra tu rostro. Quítate las gafas de sol, los sombreros o cualquier cosa que bloquee tus ojos o rasgos faciales.",
        title: "Retira las obstrucciones",
      },
    },
  },
  onboarding_modal: {
    aria: "Instrucciones para la captura facial",
    cancel_btn: "Cancelar",
    details: "No te muevas y centra el rostro en la pantalla de la cámara.",
    start_btn: "Empezar a escanear",
    title: "Mira directamente a la cámara",
  },
  processing: "Procesando...",
  sdk_aria: "Captura tu rostro",
} as const;
