/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for es_MX. Generated by core-i18n. */
export default {
  close: "Cerrar",
  error_dialogs: {
    cancel_btn: "Cancelar escaneo",
    check_internet_connection: {
      aria_description: "Conéctate a internet y vuelve a intentar escanear.",
      title: "Revisa la conexión a internet",
    },
    network_error: {
      aria_description: "Vuelve a intentar escanear. Si el problema continúa, cancela e inténtalo de nuevo más tarde.",
      title: "Error de red",
    },
    retry_btn: "Reintentar",
    scanning_not_available: {
      aria_description: "Cierra este cuadro de diálogo e inténtalo de nuevo más tarde.",
      title: "El escaneo no está disponible",
    },
    scanning_unsuccessful: {
      details: "No se pudo detectar tu rostro. Inténtalo de nuevo.",
      title: "El escaneo no se completó",
    },
  },
  feedback_messages: {
    angled_pitch: "Mire directamente a la cámara",
    angled_roll: "Mire directamente a la cámara",
    angled_yaw: "Mire directamente a la cámara",
    capture_complete_aria: "Rostro capturado correctamente",
    face_not_found: "Centra tu rostro en la pantalla",
    multiple_faces: "Solo debe verse un rostro",
    not_still: "No te muevas",
    ok: "Perfecto. No te muevas",
    too_blurry: "No te muevas",
    too_bright: "Muévete a un lugar con luz más suave",
    too_close: "Alejar más",
    too_close_to_border: "Centra tu rostro",
    too_dark: "Muévete a un lugar más iluminado",
    too_far: "Acercar más",
  },
  help_button: {
    aria_label: "Ayuda",
    tooltip: "¿Necesitas ayuda?",
  },
  help_modal: {
    aria: "Ayuda para capturar el rostro",
    back_btn: "Anterior",
    done_btn: "Finalizar",
    done_btn_aria: "Reanudar la captura del rostro",
    next_btn: "Siguiente",
    steps: {
      camera_lens: {
        details: "Revisa si el lente de la cámara tiene manchas o polvo. Un lente sucio puede desenfocar la imagen y dificultar que el sistema capture tu rostro con claridad.",
        title: "Limpie la lente de la cámara",
      },
      centered_face: {
        details: "Mira directamente a la cámara y centra tu rostro en la pantalla. Mantén el dispositivo firme y conserva una expresión neutral hasta que se capture tu rostro.",
        title: "Mantén tu rostro centrado",
      },
      lighting: {
        details: "Asegúrate de que tu rostro se vea claramente. Evita la luz muy tenue o muy intensa y mira hacia la fuente de luz en lugar de tenerla detrás de ti.",
        title: "Busca buena iluminación",
      },
      obstructions: {
        details: "Asegúrate de que nada cubra tu rostro. Quítate los lentes de sol, sombreros o cualquier cosa que cubra tus ojos o rasgos faciales.",
        title: "Quita las obstrucciones",
      },
    },
  },
  onboarding_modal: {
    aria: "Instrucciones para la captura del rostro",
    cancel_btn: "Cancelar",
    details: "Manténgase quieto y centre su rostro en la pantalla de la cámara.",
    start_btn: "Comience a escanear",
    title: "Mire directamente a la cámara",
  },
  processing: "Procesando...",
  sdk_aria: "Capture su rostro",
} as const;
