/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for fa-latn. Generated by core-i18n. */
export default {
  close: "بستن",
  error_dialogs: {
    cancel_btn: "Eskan ra laghv konid",
    check_internet_connection: {
      aria_description: "Be internet vasl shavid, sepas eskan ra dobare anjam dahid.",
      title: "Ettesal be internet ra barresi konid",
    },
    network_error: {
      aria_description: "Eskan ra dobare anjam dahid. Agar moshkel edame dasht, laghv konid va ba'dan dobare talash konid.",
      title: "Khatā-ye shabake",
    },
    retry_btn: "دوباره امتحان کنید",
    scanning_not_available: {
      aria_description: "In panjare ra ببندید va ba'dan dobare talash konid.",
      title: "Eskan dar dastres nist",
    },
    scanning_unsuccessful: {
      details: "Chehre-ye shomā tashkhis dāde nashod. Lotfan dobare talāsh konid.",
      title: "Eskan nāmovaffaq bud",
    },
  },
  feedback_messages: {
    angled_pitch: "Mostaghim be dorbin negah konid",
    angled_roll: "Mostaghim be dorbin negah konid",
    angled_yaw: "Mostaghim be dorbin negah konid",
    capture_complete_aria: "Movaffaq! Chehre sabt shod",
    face_not_found: "Chehre-ye khod ra dar markaz-e safhe gharār dahid",
    multiple_faces: "Motma'en shavid faghat yek chehre namāyān ast",
    not_still: "Bi-harekat bamanid",
    ok: "Āli ast! Bi-harekat bamanid",
    too_blurry: "Bi-harekat bamanid",
    too_bright: "Be makāni bā nur-e melāyem-tar بروید",
    too_close: "دورتر حرکت کن",
    too_close_to_border: "Chehre-ye khod ra dar markaz gharār dahid",
    too_dark: "Be makāni roshan-tar بروید",
    too_far: "نزدیکتر حرکت کن",
  },
  help_button: {
    aria_label: "کمک",
    tooltip: "به کمک نیاز دارید؟",
  },
  help_modal: {
    aria: "Rāhnamā-ye sabt-e chehre",
    back_btn: "برگشت",
    done_btn: "انجام شد",
    done_btn_aria: "Sabt-e chehre ra edame dahid",
    next_btn: "بعدی",
    steps: {
      camera_lens: {
        details: "Lenz-e dorbin ra az nazar-e lak ya gard-o-khāk barresi konid. Lenz-e kasif mitavānad aks ra tār konad va sabt-e vāzeh-e chehre-ye shomā ra sakht-tar konad.",
        title: "لنز دوربین خود را تمیز کنید",
      },
      centered_face: {
        details: "Mostaghim be dorbin negāh konid va chehre-ye khod ra dar markaz-e safhe gharār dahid. Dastgāh ra sābet negah dārid va tā zamāni ke chehre sabt mishavad, hālat-e chehre-ye bi-taraf ra hefz konid.",
        title: "Chehre-ye khod ra dar markaz negah dārid",
      },
      lighting: {
        details: "Motma'en shavid ke chehre-ye shomā be-vāzehi dide mishavad. Az nur-e kheili tārīk ya kheili roshan parhiz konid va ru be manba'-e nur bāshid, na posht be ān.",
        title: "Nur-e monāseb peydā konid",
      },
      obstructions: {
        details: "Motma'en shavid ke chizi chehre-ye shomā rā napushānde ast. Aynak-e āftābi, kolāh yā har chizi rā ke cheshmhā yā vizhegihā-ye chehre rā mipushānad, bardārid.",
        title: "Mavāne' rā bardārid",
      },
    },
  },
  onboarding_modal: {
    aria: "Rahnemay-e sabt-e chehre",
    cancel_btn: "Laghv",
    details: "Bi-harekat bemanid va chehre-ye khod ra dar markaz-e safhe-ye dorbin qarar dahid.",
    start_btn: "شروع اسکن",
    title: "Mostaghim be dorbin negah konid",
  },
  processing: "Dar hal-e pardazesh...",
  sdk_aria: "Chehre-ye khod ra sabt konid",
} as const;
