/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for fi. Generated by core-i18n. */
export default {
  close: "Sulje",
  error_dialogs: {
    cancel_btn: "Peruuta skannaus",
    check_internet_connection: {
      aria_description: "Yhdistä internetiin ja yritä sitten skannausta uudelleen.",
      title: "Tarkista internetyhteys",
    },
    network_error: {
      aria_description: "Yritä skannausta uudelleen. Jos ongelma jatkuu, peruuta ja yritä myöhemmin uudelleen.",
      title: "Verkkovirhe",
    },
    retry_btn: "Yritä uudelleen",
    scanning_not_available: {
      aria_description: "Sulje tämä valintaikkuna ja yritä myöhemmin uudelleen.",
      title: "Skannaus ei ole käytettävissä",
    },
    scanning_unsuccessful: {
      details: "Kasvojasi ei havaittu. Yritä uudelleen.",
      title: "Skannaus epäonnistui",
    },
  },
  feedback_messages: {
    angled_pitch: "Katso suoraan kameraan",
    angled_roll: "Katso suoraan kameraan",
    angled_yaw: "Katso suoraan kameraan",
    capture_complete_aria: "Kasvot tallennettu onnistuneesti",
    face_not_found: "Aseta kasvosi näytön keskelle",
    multiple_faces: "Vain yhdet kasvot saavat näkyä",
    not_still: "Pysy paikallasi",
    ok: "Hyvä! Pysy paikallasi",
    too_blurry: "Pysy paikallasi",
    too_bright: "Siirry pehmeämpään valaistukseen",
    too_close: "Siirry kauemmas",
    too_close_to_border: "Keskitä kasvosi",
    too_dark: "Siirry kirkkaampaan paikkaan",
    too_far: "Siirry lähemmäs",
  },
  help_button: {
    aria_label: "Ohje",
    tooltip: "Tarvitsetko apua?",
  },
  help_modal: {
    aria: "Ohjeita kasvojen tallennukseen",
    back_btn: "Takaisin",
    done_btn: "Valmis",
    done_btn_aria: "Jatka kasvokuvausta",
    next_btn: "Seuraava",
    steps: {
      camera_lens: {
        details: "Tarkista, ettei kameran linssissä ole tahroja tai pölyä. Likainen linssi voi sumentaa kuvasi ja vaikeuttaa kasvojesi selkeää tallentamista.",
        title: "Puhdista kameran linssi",
      },
      centered_face: {
        details: "Katso suoraan kameraan ja keskitä kasvosi näytölle. Pidä laite vakaana ja ilme neutraalina, kunnes kasvosi on tallennettu.",
        title: "Pidä kasvosi keskellä",
      },
      lighting: {
        details: "Varmista, että kasvosi näkyvät selkeästi. Vältä hyvin hämärää tai kirkasta valaistusta ja älä asetu niin, että valonlähde on takanasi.",
        title: "Etsi hyvä valaistus",
      },
      obstructions: {
        details: "Varmista, ettei mikään peitä kasvojasi. Poista aurinkolasit, hatut ja kaikki, mikä peittää silmäsi tai kasvonpiirteitäsi.",
        title: "Poista esteet",
      },
    },
  },
  onboarding_modal: {
    aria: "Kasvokuvauksen ohjeet",
    cancel_btn: "Peruuta",
    details: "Pysy paikallasi ja pidä kasvosi keskellä kameranäkymää.",
    start_btn: "Aloita skannaus",
    title: "Katso suoraan kameraan",
  },
  processing: "Käsitellään...",
  sdk_aria: "Kuvaa kasvosi",
} as const;
