/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for fil. Generated by core-i18n. */
export default {
  close: "Isara",
  error_dialogs: {
    cancel_btn: "Kanselahin ang pag-scan",
    check_internet_connection: {
      aria_description: "Kumonekta sa internet, pagkatapos ay subukang mag-scan muli.",
      title: "Suriin ang koneksyon sa internet",
    },
    network_error: {
      aria_description: "Subukang mag-scan muli. Kung magpapatuloy ang problema, kanselahin at subukan muli mamaya.",
      title: "Error sa network",
    },
    retry_btn: "Subukan ulit",
    scanning_not_available: {
      aria_description: "Isara ang dialog na ito at subukan muli mamaya.",
      title: "Hindi available ang pag-scan",
    },
    scanning_unsuccessful: {
      details: "Hindi makita ang iyong mukha. Subukan muli.",
      title: "Hindi matagumpay ang pag-scan",
    },
  },
  feedback_messages: {
    angled_pitch: "Tumingin nang diretso sa camera",
    angled_roll: "Tumingin nang diretso sa camera",
    angled_yaw: "Tumingin nang diretso sa camera",
    capture_complete_aria: "Tagumpay! Nakunan ang iyong mukha",
    face_not_found: "Igitna ang iyong mukha sa screen",
    multiple_faces: "Isang mukha lang ang dapat makita",
    not_still: "Huwag gumalaw",
    ok: "Ayos! Huwag gumalaw",
    too_blurry: "Huwag gumalaw",
    too_bright: "Lumipat sa lugar na mas banayad ang ilaw",
    too_close: "Ilayo pa",
    too_close_to_border: "Igitna ang iyong mukha",
    too_dark: "Lumipat sa mas maliwanag na lugar",
    too_far: "Ilapit pa",
  },
  help_button: {
    aria_label: "Tulong",
    tooltip: "Kailangan ng tulong?",
  },
  help_modal: {
    aria: "Tulong sa pagkuha ng mukha",
    back_btn: "Bumalik",
    done_btn: "Tapos na",
    done_btn_aria: "Ipagpatuloy ang pagkuha ng mukha",
    next_btn: "Susunod",
    steps: {
      camera_lens: {
        details: "Suriin kung may mantsa o alikabok ang lente ng iyong camera. Maaaring lumabo ang iyong larawan dahil sa maruming lente at maging mas mahirap makuha nang malinaw ang iyong mukha.",
        title: "Linisin ang mga lens ng camera mo",
      },
      centered_face: {
        details: "Tumingin nang diretso sa camera at igitna ang iyong mukha sa screen. Panatilihing matatag ang iyong device at panatilihing neutral ang iyong ekspresyon hanggang makuha ang iyong mukha.",
        title: "Panatilihing nasa gitna ang iyong mukha",
      },
      lighting: {
        details: "Tiyaking malinaw na nakikita ang iyong mukha. Iwasan ang napakadilim o napakaliwanag na ilaw, at tiyaking nasa harap mo ang pinagmumulan ng ilaw, hindi sa likuran mo.",
        title: "Humanap ng magandang ilaw",
      },
      obstructions: {
        details: "Tiyaking walang nakatakip sa iyong mukha. Alisin ang salaming pang-araw, sumbrero, o anumang nakaharang sa iyong mga mata o bahagi ng mukha.",
        title: "Alisin ang mga nakaharang",
      },
    },
  },
  onboarding_modal: {
    aria: "Mga tagubilin sa pagkuha ng mukha",
    cancel_btn: "Kanselahin",
    details: "Manatiling hindi gumagalaw at igitna ang iyong mukha sa screen ng camera.",
    start_btn: "Simulan ang Pag-scan",
    title: "Tumingin nang diretso sa camera",
  },
  processing: "Pinoproseso...",
  sdk_aria: "Kunan ang iyong mukha",
} as const;
