/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for fr. Generated by core-i18n. */
export default {
  close: "Fermer",
  error_dialogs: {
    cancel_btn: "Annuler la capture",
    check_internet_connection: {
      aria_description: "Connectez-vous à Internet, puis réessayez la capture.",
      title: "Vérifiez votre connexion Internet",
    },
    network_error: {
      aria_description: "Réessayez la capture. Si le problème persiste, annulez et réessayez plus tard.",
      title: "Erreur réseau",
    },
    retry_btn: "Réessayez",
    scanning_not_available: {
      aria_description: "Fermez cette boîte de dialogue et réessayez plus tard.",
      title: "Capture indisponible",
    },
    scanning_unsuccessful: {
      details: "Impossible de détecter votre visage. Veuillez réessayer.",
      title: "Échec de la capture",
    },
  },
  feedback_messages: {
    angled_pitch: "Regardez droit dans la caméra",
    angled_roll: "Regardez droit dans la caméra",
    angled_yaw: "Regardez droit dans la caméra",
    capture_complete_aria: "Visage capturé avec succès",
    face_not_found: "Centrez votre visage à l’écran",
    multiple_faces: "Veillez à ce qu’un seul visage soit visible",
    not_still: "Ne bougez pas",
    ok: "Parfait ! Ne bougez pas",
    too_blurry: "Ne bougez pas",
    too_bright: "Placez-vous dans un endroit moins éclairé",
    too_close: "Éloignez-vous",
    too_close_to_border: "Centrez votre visage",
    too_dark: "Placez-vous dans un endroit plus éclairé",
    too_far: "Rapprochez-vous",
  },
  help_button: {
    aria_label: "Aide",
    tooltip: "Besoin d'aide ?",
  },
  help_modal: {
    aria: "Aide sur la capture du visage",
    back_btn: "Retour",
    done_btn: "Terminé",
    done_btn_aria: "Reprendre la capture du visage",
    next_btn: "Suivant",
    steps: {
      camera_lens: {
        details: "Vérifiez que l’objectif de votre caméra ne présente pas de traces ou de poussière. Un objectif sale peut rendre votre photo floue et empêcher une capture nette de votre visage.",
        title: "Nettoyez l’objectif de votre appareil photo",
      },
      centered_face: {
        details: "Regardez directement la caméra et centrez votre visage à l’écran. Tenez votre appareil immobile et gardez une expression neutre jusqu’à ce que votre visage soit capturé.",
        title: "Gardez votre visage centré",
      },
      lighting: {
        details: "Assurez-vous que votre visage est clairement visible. Évitez les endroits très sombres et les lumières trop vives. Placez-vous face à la source de lumière plutôt que dos à celle-ci.",
        title: "Trouvez un bon éclairage",
      },
      obstructions: {
        details: "Assurez-vous que rien ne couvre votre visage. Retirez les lunettes de soleil, chapeaux ou tout autre élément qui masque vos yeux ou vos traits du visage.",
        title: "Retirez ce qui couvre votre visage",
      },
    },
  },
  onboarding_modal: {
    aria: "Instructions de capture du visage",
    cancel_btn: "Annuler",
    details: "Restez immobile et centrez votre visage dans le champ de la caméra.",
    start_btn: "Commencer à scanner",
    title: "Regardez droit dans la caméra",
  },
  processing: "Traitement en cours…",
  sdk_aria: "Capturez votre visage",
} as const;
