/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for fr_CA. Generated by core-i18n. */
export default {
  close: "Fermer",
  error_dialogs: {
    cancel_btn: "Annuler la numérisation",
    check_internet_connection: {
      aria_description: "Connectez-vous à Internet, puis réessayez la numérisation.",
      title: "Vérifiez votre connexion Internet",
    },
    network_error: {
      aria_description: "Réessayez la numérisation. Si le problème persiste, annulez et réessayez plus tard.",
      title: "Erreur de réseau",
    },
    retry_btn: "Réessayer",
    scanning_not_available: {
      aria_description: "Fermez cette boîte de dialogue et réessayez plus tard.",
      title: "Numérisation non disponible",
    },
    scanning_unsuccessful: {
      details: "Votre visage n’a pas été détecté. Réessayez.",
      title: "Échec de la numérisation",
    },
  },
  feedback_messages: {
    angled_pitch: "Regardez directement la caméra",
    angled_roll: "Regardez directement la caméra",
    angled_yaw: "Regardez directement la caméra",
    capture_complete_aria: "Visage capturé",
    face_not_found: "Centrez votre visage à l’écran",
    multiple_faces: "Assurez-vous qu’un seul visage est visible",
    not_still: "Restez immobile",
    ok: "Parfait ! Restez immobile",
    too_blurry: "Restez immobile",
    too_bright: "Déplacez-vous vers un endroit où l’éclairage est plus doux",
    too_close: "Éloignez-vous",
    too_close_to_border: "Centrez votre visage",
    too_dark: "Déplacez-vous vers un endroit plus éclairé",
    too_far: "Rapprochez-vous",
  },
  help_button: {
    aria_label: "Aide",
    tooltip: "Besoin d'aide?",
  },
  help_modal: {
    aria: "Aide à la capture du visage",
    back_btn: "Retour",
    done_btn: "Terminé",
    done_btn_aria: "Reprendre la capture du visage",
    next_btn: "Suivant",
    steps: {
      camera_lens: {
        details: "Vérifiez si l’objectif de votre caméra est taché ou poussiéreux. Un objectif sale peut rendre votre image floue et compliquer la capture nette de votre visage.",
        title: "Nettoyez l'objectif de votre appareil photo",
      },
      centered_face: {
        details: "Regardez directement la caméra et centrez votre visage à l’écran. Gardez votre appareil immobile et conservez une expression neutre jusqu’à ce que votre visage soit capturé.",
        title: "Gardez votre visage centré",
      },
      lighting: {
        details: "Assurez-vous que votre visage est clairement visible. Évitez un éclairage trop faible ou trop intense et placez-vous face à la source de lumière plutôt que dos à celle-ci.",
        title: "Trouvez un bon éclairage",
      },
      obstructions: {
        details: "Assurez-vous que rien ne couvre votre visage. Retirez vos lunettes de soleil, votre chapeau ou tout autre objet qui bloque vos yeux ou vos traits du visage.",
        title: "Dégagez votre visage",
      },
    },
  },
  onboarding_modal: {
    aria: "Instructions pour la capture du visage",
    cancel_btn: "Annuler",
    details: "Restez immobile et centrez votre visage dans le cadre de la caméra.",
    start_btn: "Commencer le balayage",
    title: "Regardez directement la caméra",
  },
  processing: "Traitement en cours...",
  sdk_aria: "Capturez votre visage",
} as const;
