/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ha. Generated by core-i18n. */
export default {
  close: "Rufe",
  error_dialogs: {
    cancel_btn: "Soke bincike",
    check_internet_connection: {
      aria_description: "Haɗa zuwa intanet, sannan a sake gwada bincike.",
      title: "Duba haɗin intanet",
    },
    network_error: {
      aria_description: "Sake gwada bincike. Idan matsalar ta ci gaba, soke kuma a sake gwadawa daga baya.",
      title: "Kuskuren hanyar sadarwa",
    },
    retry_btn: "Sake gwadawa",
    scanning_not_available: {
      aria_description: "Rufe wannan akwatin magana kuma a sake gwadawa daga baya.",
      title: "Ba a samun bincike",
    },
    scanning_unsuccessful: {
      details: "Ba a iya gano fuskarka ba. Da fatan za a sake gwadawa.",
      title: "Binciken bai yi nasara ba",
    },
  },
  feedback_messages: {
    angled_pitch: "Dubi kamara kai tsaye",
    angled_roll: "Dubi kamara kai tsaye",
    angled_yaw: "Dubi kamara kai tsaye",
    capture_complete_aria: "An yi nasara! An kama fuskarka",
    face_not_found: "Sanya fuskarka a tsakiyar allo",
    multiple_faces: "Fuska ɗaya kawai ya kamata a gani",
    not_still: "Tsaya cak",
    ok: "Daidai! Tsaya cak",
    too_blurry: "Tsaya cak",
    too_bright: "Matsa zuwa wuri mai haske mai laushi",
    too_close: "Matsa baya",
    too_close_to_border: "Sanya fuskarka a tsakiya",
    too_dark: "Matsa zuwa wuri mai haske",
    too_far: "Matsa kusa",
  },
  help_button: {
    aria_label: "Taimako",
    tooltip: "Ana buƙatar taimako?",
  },
  help_modal: {
    aria: "Taimako kan kama fuska",
    back_btn: "Baya",
    done_btn: "Kammala",
    done_btn_aria: "Ci gaba da ɗaukar fuska",
    next_btn: "Gaba",
    steps: {
      camera_lens: {
        details: "Duba ruwan tabarau na kyamararka don tabo ko ƙura. Ruwan tabarau mai datti na iya sa hotonka ya yi dusashe kuma ya sa tsarin ya yi wahalar kama fuskarka a sarari.",
        title: "Ku tsaftace gilashin kamerarku",
      },
      centered_face: {
        details: "Kalli kyamara kai tsaye kuma sanya fuskarka a tsakiyar allo. Riƙe na'urarka da kyau kada ta motsa, kuma ka kasance da yanayin fuska na tsaka-tsaki har sai an kama fuskarka.",
        title: "Riƙe fuskarka a tsakiya",
      },
      lighting: {
        details: "Tabbatar ana ganin fuskarka a sarari. Guji wurare masu duhu sosai ko haske mai ƙarfi sosai, kuma ka fuskanci tushen haske maimakon ya kasance a bayanka.",
        title: "Nemi haske mai kyau",
      },
      obstructions: {
        details: "Tabbatar babu abin da ya rufe fuskarka. Cire tabarau masu duhu, huluna, ko duk wani abu da ke toshe idanunka ko fasalin fuskarka.",
        title: "Cire abubuwan da ke toshewa",
      },
    },
  },
  onboarding_modal: {
    aria: "Umarnin ɗaukar fuska",
    cancel_btn: "Soke",
    details: "Tabbatar ka tsaya cak kuma ka sanya fuskarka a tsakiyar allon kamara.",
    start_btn: "Fara ɗaukar hoto",
    title: "Dubi kamara kai tsaye",
  },
  processing: "Ana sarrafawa...",
  sdk_aria: "Ɗauki fuskarka",
} as const;
