/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for he. Generated by core-i18n. */
export default {
  close: "סגור",
  error_dialogs: {
    cancel_btn: "ביטול הסריקה",
    check_internet_connection: {
      aria_description: "התחברו לאינטרנט ולאחר מכן נסו לסרוק שוב.",
      title: "בדקו את החיבור לאינטרנט",
    },
    network_error: {
      aria_description: "נסו לסרוק שוב. אם הבעיה נמשכת, בטלו ונסו שוב מאוחר יותר.",
      title: "שגיאת רשת",
    },
    retry_btn: "לנסות שוב",
    scanning_not_available: {
      aria_description: "סגרו את תיבת הדו-שיח הזו ונסו שוב מאוחר יותר.",
      title: "הסריקה אינה זמינה",
    },
    scanning_unsuccessful: {
      details: "לא ניתן לזהות את פניכם. נסו שוב.",
      title: "הסריקה לא הושלמה",
    },
  },
  feedback_messages: {
    angled_pitch: "הביטו ישר למצלמה",
    angled_roll: "הביטו ישר למצלמה",
    angled_yaw: "הביטו ישר למצלמה",
    capture_complete_aria: "הפנים נלכדו בהצלחה",
    face_not_found: "מקמו את פניכם במרכז המסך",
    multiple_faces: "ודאו שרק פניכם מופיעות בפריים",
    not_still: "הישארו ללא תזוזה",
    ok: "מצוין! הישארו ללא תזוזה",
    too_blurry: "הישארו ללא תזוזה",
    too_bright: "עברו למקום עם תאורה רכה יותר",
    too_close: "התרחק/י",
    too_close_to_border: "מרכזו את פניכם",
    too_dark: "עברו למקום מואר יותר",
    too_far: "קרב/י",
  },
  help_button: {
    aria_label: "עזרה",
    tooltip: "זקוקים לעזרה?",
  },
  help_modal: {
    aria: "עזרה ללכידת פנים",
    back_btn: "חזור",
    done_btn: "בוצע",
    done_btn_aria: "המשך לכידת פנים",
    next_btn: "הבא",
    steps: {
      camera_lens: {
        details: "בדקו אם יש כתמים או אבק על עדשת המצלמה. עדשה מלוכלכת עלולה לטשטש את התמונה ולהקשות על המערכת ללכוד את פניכם בבירור.",
        title: "יש לנקות את עדשת המצלמה",
      },
      centered_face: {
        details: "הביטו ישר למצלמה ומקמו את פניכם במרכז המסך. החזיקו את המכשיר יציב ושמרו על הבעה ניטרלית עד ללכידת פניכם.",
        title: "שמרו את פניכם במרכז",
      },
      lighting: {
        details: "ודאו שפניכם נראות בבירור. הימנעו מתאורה חלשה מאוד או חזקה מאוד, ופנו אל מקור האור במקום לעמוד כשמקור האור מאחוריכם.",
        title: "מצאו תאורה טובה",
      },
      obstructions: {
        details: "ודאו ששום דבר אינו מכסה את פניכם. הסירו משקפי שמש, כובעים או כל דבר שמסתיר את עיניכם או את תווי הפנים.",
        title: "הסירו דברים שמסתירים את הפנים",
      },
    },
  },
  onboarding_modal: {
    aria: "הוראות ללכידת פנים",
    cancel_btn: "ביטול",
    details: "אל תזוזו. מקמו את פניכם במרכז מסך המצלמה.",
    start_btn: "התחלת סריקה",
    title: "הביטו ישר למצלמה",
  },
  processing: "מעבד...",
  sdk_aria: "צלמו את פניכם",
} as const;
