/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for hr. Generated by core-i18n. */
export default {
  close: "Zatvori",
  error_dialogs: {
    cancel_btn: "Prekini skeniranje",
    check_internet_connection: {
      aria_description: "Povežite se s internetom, a zatim pokušajte ponovno skenirati.",
      title: "Provjerite internetsku vezu",
    },
    network_error: {
      aria_description: "Pokušajte ponovno skenirati. Ako se problem nastavi, prekinite skeniranje i pokušajte ponovno kasnije.",
      title: "Pogreška mreže",
    },
    retry_btn: "U redu",
    scanning_not_available: {
      aria_description: "Zatvorite ovaj prozor i pokušajte ponovno kasnije.",
      title: "Skeniranje nije dostupno",
    },
    scanning_unsuccessful: {
      details: "Nije moguće detektirati lice. Molimo pokušajte ponovno.",
      title: "Skeniranje nije uspjelo",
    },
  },
  feedback_messages: {
    angled_pitch: "Gledajte ravno u kameru",
    angled_roll: "Gledajte ravno u kameru",
    angled_yaw: "Gledajte ravno u kameru",
    capture_complete_aria: "Uspjeh! Lice je snimljeno",
    face_not_found: "Centrirajte lice na zaslonu",
    multiple_faces: "Samo jedno lice smije biti vidljivo",
    not_still: "Ostanite mirni",
    ok: "Odlično! Ostanite mirni",
    too_blurry: "Ostanite mirni",
    too_bright: "Pomaknite se na slabije osvijetljeno mjesto",
    too_close: "Udaljite dokument",
    too_close_to_border: "Centrirajte lice",
    too_dark: "Pomaknite se na više osvijetljeno mjesto",
    too_far: "Približite dokument",
  },
  help_button: {
    aria_label: "Pomoć",
    tooltip: "Trebate pomoć?",
  },
  help_modal: {
    aria: "Pomoć za snimanje lica",
    back_btn: "Natrag",
    done_btn: "OK",
    done_btn_aria: "Nastavite snimanje lica",
    next_btn: "Dalje",
    steps: {
      camera_lens: {
        details: "Provjerite je li kamera čista. Prljava kamera uzrokuje zamućenje slike i otežava sustavu jasno snimanje vašeg lica.",
        title: "Očistite kameru",
      },
      centered_face: {
        details: "Gledajte ravno u kameru i centrirajte lice na ekranu. Držite uređaj mirno i zadržite neutralan izraz lica dok se lice ne snimi.",
        title: "Držite lice centrirano",
      },
      lighting: {
        details: "Pripazite da je vaše lice jasno vidljivo. Izbjegavajte vrlo tamno ili jako osvjetljenje te pazite da izvor svjetla bude ispred vas, a ne iza vas.",
        title: "Pronađite dobro osvjetljenje",
      },
      obstructions: {
        details: "Pripazite da ništa ne prekriva vaše lice. Uklonite sunčane naočale, kape ili bilo što što zaklanja oči ili crte lica.",
        title: "Uklonite sve što prekriva lice",
      },
    },
  },
  onboarding_modal: {
    aria: "Upute za snimanje lica",
    cancel_btn: "Odustani",
    details: "Pripazite da ostanete mirni i držite lice centrirano na ekranu vašeg uređaja.",
    start_btn: "Započnite skeniranje",
    title: "Gledajte ravno u kameru",
  },
  processing: "Obrađuje se...",
  sdk_aria: "Snimite svoje lice",
} as const;
