/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for hu. Generated by core-i18n. */
export default {
  close: "Bezárás",
  error_dialogs: {
    cancel_btn: "Beolvasás megszakítása",
    check_internet_connection: {
      aria_description: "Csatlakozzon az internethez, majd próbálja újra a beolvasást.",
      title: "Ellenőrizze az internetkapcsolatot",
    },
    network_error: {
      aria_description: "Próbálja újra a beolvasást. Ha a probléma továbbra is fennáll, szakítsa meg a beolvasást, és próbálja meg később.",
      title: "Hálózati hiba",
    },
    retry_btn: "Próbálja újra",
    scanning_not_available: {
      aria_description: "Zárja be ezt a párbeszédablakot, és próbálja meg később.",
      title: "A beolvasás nem érhető el",
    },
    scanning_unsuccessful: {
      details: "Nem sikerült észlelni az arcát. Próbálja újra.",
      title: "A beolvasás sikertelen",
    },
  },
  feedback_messages: {
    angled_pitch: "Nézzen egyenesen a kamerába",
    angled_roll: "Nézzen egyenesen a kamerába",
    angled_yaw: "Nézzen egyenesen a kamerába",
    capture_complete_aria: "Sikerült! Az arc rögzítve.",
    face_not_found: "Igazítsa az arcát a képernyő közepére",
    multiple_faces: "Csak egy arc legyen látható",
    not_still: "Maradjon mozdulatlan",
    ok: "Tökéletes! Maradjon mozdulatlan",
    too_blurry: "Maradjon mozdulatlan",
    too_bright: "Menjen lágyabb megvilágítású helyre",
    too_close: "Menjen távolabb",
    too_close_to_border: "Igazítsa az arcát középre",
    too_dark: "Menjen világosabb helyre",
    too_far: "Menjen közelebb",
  },
  help_button: {
    aria_label: "Súgó",
    tooltip: "Segíthetünk bármiben?",
  },
  help_modal: {
    aria: "Súgó az arcrögzítéshez",
    back_btn: "Vissza",
    done_btn: "Kész",
    done_btn_aria: "Folytassa az arcrögzítést",
    next_btn: "Következő",
    steps: {
      camera_lens: {
        details: "Ellenőrizze, hogy nincs-e maszat vagy por a kameralencsén. A szennyezett lencse elhomályosíthatja a képet, és megnehezítheti az arc tiszta rögzítését.",
        title: "Tisztítsa meg a kameralencsét",
      },
      centered_face: {
        details: "Nézzen egyenesen a kamerába, és igazítsa az arcát a képernyő közepére. Tartsa stabilan az eszközt, és tartson semleges arckifejezést, amíg az arcát rögzíti a rendszer.",
        title: "Tartsa az arcát középen",
      },
      lighting: {
        details: "Győződjön meg arról, hogy az arca jól látható. Kerülje a nagyon sötét vagy nagyon erős megvilágítást, és a fényforrás felé nézzen, ne háttal álljon annak.",
        title: "Keressen megfelelő megvilágítást",
      },
      obstructions: {
        details: "Győződjön meg arról, hogy semmi nem takarja az arcát. Vegye le a napszemüveget, a fejfedőt vagy bármit, ami eltakarja a szemét vagy az arcvonásait.",
        title: "Távolítsa el, ami eltakarja az arcát",
      },
    },
  },
  onboarding_modal: {
    aria: "Arcrögzítési utasítások",
    cancel_btn: "Mégse",
    details: "Maradjon mozdulatlan, és igazítsa az arcát a kamerakép közepére.",
    start_btn: "Szkennelés megkezdése",
    title: "Nézzen egyenesen a kamerába",
  },
  processing: "Feldolgozás...",
  sdk_aria: "Rögzítse az arcát",
} as const;
