/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for id. Generated by core-i18n. */
export default {
  close: "Tutup",
  error_dialogs: {
    cancel_btn: "Batalkan pemindaian",
    check_internet_connection: {
      aria_description: "Sambungkan ke internet, lalu coba pindai lagi.",
      title: "Periksa koneksi internet",
    },
    network_error: {
      aria_description: "Coba pindai lagi. Jika masalah berlanjut, batalkan dan coba lagi nanti.",
      title: "Kesalahan jaringan",
    },
    retry_btn: "Coba Lagi",
    scanning_not_available: {
      aria_description: "Tutup dialog ini dan coba lagi nanti.",
      title: "Pemindaian tidak tersedia",
    },
    scanning_unsuccessful: {
      details: "Wajah Anda tidak dapat dideteksi. Coba lagi.",
      title: "Pemindaian tidak berhasil",
    },
  },
  feedback_messages: {
    angled_pitch: "Hadapkan wajah lurus ke kamera",
    angled_roll: "Hadapkan wajah lurus ke kamera",
    angled_yaw: "Hadapkan wajah lurus ke kamera",
    capture_complete_aria: "Berhasil! Wajah tertangkap",
    face_not_found: "Posisikan wajah Anda di tengah layar",
    multiple_faces: "Hanya satu wajah yang boleh terlihat",
    not_still: "Tetap diam",
    ok: "Sempurna! Tetap diam",
    too_blurry: "Tetap diam",
    too_bright: "Pindah ke tempat dengan pencahayaan yang lebih lembut",
    too_close: "Mohon jauhkan",
    too_close_to_border: "Posisikan wajah Anda di tengah",
    too_dark: "Pindah ke tempat yang lebih terang",
    too_far: "Mohon dekatkan",
  },
  help_button: {
    aria_label: "Bantuan",
    tooltip: "Perlu bantuan?",
  },
  help_modal: {
    aria: "Bantuan penangkapan wajah",
    back_btn: "Kembali",
    done_btn: "Selesai",
    done_btn_aria: "Lanjutkan pengambilan wajah",
    next_btn: "Berikutnya",
    steps: {
      camera_lens: {
        details: "Periksa apakah ada noda atau debu pada lensa kamera Anda. Lensa yang kotor dapat membuat foto buram dan menyulitkan sistem menangkap wajah Anda dengan jelas.",
        title: "Bersihkan lensa kamera",
      },
      centered_face: {
        details: "Tatap kamera secara langsung dan posisikan wajah Anda di tengah layar. Pegang perangkat Anda dengan stabil dan pertahankan ekspresi netral hingga wajah Anda tertangkap.",
        title: "Jaga wajah Anda tetap di tengah",
      },
      lighting: {
        details: "Pastikan wajah Anda terlihat jelas. Hindari pencahayaan yang sangat gelap atau sangat terang, dan hadaplah ke sumber cahaya, bukan membelakanginya.",
        title: "Cari pencahayaan yang baik",
      },
      obstructions: {
        details: "Pastikan tidak ada yang menutupi wajah Anda. Lepaskan kacamata hitam, topi, atau apa pun yang menghalangi mata atau fitur wajah Anda.",
        title: "Singkirkan penghalang",
      },
    },
  },
  onboarding_modal: {
    aria: "Petunjuk pengambilan wajah",
    cancel_btn: "Batal",
    details: "Tetap diam dan posisikan wajah Anda di tengah layar kamera.",
    start_btn: "Mulai Pemindaian",
    title: "Hadapkan wajah lurus ke kamera",
  },
  processing: "Memproses...",
  sdk_aria: "Ambil gambar wajah Anda",
} as const;
