/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for is. Generated by core-i18n. */
export default {
  close: "Loka",
  error_dialogs: {
    cancel_btn: "Hætta við skönnun",
    check_internet_connection: {
      aria_description: "Tengstu internetinu og reyndu síðan að skanna aftur.",
      title: "Athugaðu internettenginguna",
    },
    network_error: {
      aria_description: "Reyndu að skanna aftur. Ef vandamálið heldur áfram skaltu hætta við og reyna aftur síðar.",
      title: "Netvilla",
    },
    retry_btn: "Reynið aftur",
    scanning_not_available: {
      aria_description: "Lokaðu þessum glugga og reyndu aftur síðar.",
      title: "Skönnun ekki tiltæk",
    },
    scanning_unsuccessful: {
      details: "Ekki tókst að greina andlit þitt. Reyndu aftur.",
      title: "Skönnun mistókst",
    },
  },
  feedback_messages: {
    angled_pitch: "Horfðu beint í myndavélina",
    angled_roll: "Horfðu beint í myndavélina",
    angled_yaw: "Horfðu beint í myndavélina",
    capture_complete_aria: "Tókst! Andlitsmynd tekin",
    face_not_found: "Settu andlit þitt á miðjan skjáinn",
    multiple_faces: "Aðeins eitt andlit má vera sýnilegt",
    not_still: "Haltu kyrru fyrir",
    ok: "Fullkomið! Haltu kyrru fyrir",
    too_blurry: "Haltu kyrru fyrir",
    too_bright: "Farðu á stað með mýkri lýsingu",
    too_close: "Færið fjær",
    too_close_to_border: "Settu andlit þitt í miðjuna",
    too_dark: "Farðu á bjartari stað",
    too_far: "Færið nær",
  },
  help_button: {
    aria_label: "Hjálp",
    tooltip: "Þarftu aðstoð?",
  },
  help_modal: {
    aria: "Hjálp við andlitsmyndatöku",
    back_btn: "Til baka",
    done_btn: "Lokið",
    done_btn_aria: "Halda áfram andlitsmyndatöku",
    next_btn: "Áfram",
    steps: {
      camera_lens: {
        details: "Athugaðu hvort fingraför eða ryk séu á myndavélarlinsunni. Óhrein linsa getur gert myndina óskýra og torveldað kerfinu að ná skýrri mynd af andliti þínu.",
        title: "Hreinsið myndavélalinsuna",
      },
      centered_face: {
        details: "Horfðu beint í myndavélina og settu andlit þitt á miðjan skjáinn. Haltu tækinu stöðugu og hafðu hlutlausan svip þar til mynd hefur verið tekin af andliti þínu.",
        title: "Haltu andlitinu í miðjunni",
      },
      lighting: {
        details: "Gakktu úr skugga um að andlit þitt sé vel sýnilegt. Forðastu mjög dimma eða mjög bjarta lýsingu og snúðu þér að ljósgjafanum í stað þess að hafa hann fyrir aftan þig.",
        title: "Finndu góða lýsingu",
      },
      obstructions: {
        details: "Gakktu úr skugga um að ekkert hylji andlit þitt. Taktu af þér sólgleraugu, hatt eða annað sem hylur augun eða andlitseinkenni.",
        title: "Fjarlægðu það sem hylur andlitið",
      },
    },
  },
  onboarding_modal: {
    aria: "Leiðbeiningar um andlitsmyndatöku",
    cancel_btn: "Hætta við",
    details: "Haltu kyrru fyrir og hafðu andlitið í miðju myndavélarskjásins.",
    start_btn: "Byrja að skanna",
    title: "Horfðu beint í myndavélina",
  },
  processing: "Vinnsla...",
  sdk_aria: "Taktu mynd af andlitinu þínu",
} as const;
