/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for it. Generated by core-i18n. */
export default {
  close: "Chiudi",
  error_dialogs: {
    cancel_btn: "Annulla la scansione",
    check_internet_connection: {
      aria_description: "Connettiti a Internet, quindi riprova la scansione.",
      title: "Controlla la connessione Internet",
    },
    network_error: {
      aria_description: "Riprova la scansione. Se il problema persiste, annulla e riprova più tardi.",
      title: "Errore di rete",
    },
    retry_btn: "Riprova",
    scanning_not_available: {
      aria_description: "Chiudi questa finestra di dialogo e riprova più tardi.",
      title: "Scansione non disponibile",
    },
    scanning_unsuccessful: {
      details: "Impossibile rilevare il tuo viso. Riprova.",
      title: "Scansione non riuscita",
    },
  },
  feedback_messages: {
    angled_pitch: "Guarda dritto verso la fotocamera",
    angled_roll: "Guarda dritto verso la fotocamera",
    angled_yaw: "Guarda dritto verso la fotocamera",
    capture_complete_aria: "Operazione riuscita. Viso acquisito",
    face_not_found: "Centra il viso sullo schermo",
    multiple_faces: "Assicurati che sia visibile un solo viso",
    not_still: "Rimani fermo",
    ok: "Perfetto. Rimani fermo",
    too_blurry: "Rimani fermo",
    too_bright: "Spostati in un punto con luce più soffusa",
    too_close: "Spostati più lontano",
    too_close_to_border: "Centra il viso",
    too_dark: "Spostati in un punto più luminoso",
    too_far: "Avvicinati",
  },
  help_button: {
    aria_label: "Aiuto",
    tooltip: "Ti serve aiuto?",
  },
  help_modal: {
    aria: "Guida all'acquisizione del viso",
    back_btn: "Indietro",
    done_btn: "Fatto",
    done_btn_aria: "Riprendi l'acquisizione del volto",
    next_btn: "Avanti",
    steps: {
      camera_lens: {
        details: "Controlla che l'obiettivo della fotocamera non presenti macchie o polvere. Un obiettivo sporco può rendere sfocata la foto e rendere più difficile per il sistema acquisire chiaramente il viso.",
        title: "Pulisci la lente della fotocamera",
      },
      centered_face: {
        details: "Guarda dritto nella fotocamera e centra il viso sullo schermo. Tieni fermo il dispositivo e mantieni un'espressione neutra finché il viso non viene acquisito.",
        title: "Tieni il viso al centro",
      },
      lighting: {
        details: "Assicurati che il viso sia ben visibile. Evita ambienti molto bui o con luce troppo intensa e rivolgiti verso la fonte di luce, anziché averla alle spalle.",
        title: "Trova una buona illuminazione",
      },
      obstructions: {
        details: "Assicurati che nulla copra il viso. Rimuovi occhiali da sole, cappelli o qualsiasi altro elemento che copra gli occhi o i lineamenti del viso.",
        title: "Rimuovi ciò che copre il viso",
      },
    },
  },
  onboarding_modal: {
    aria: "Istruzioni per l'acquisizione del volto",
    cancel_btn: "Annulla",
    details: "Rimani immobile e centra il volto nell'inquadratura della fotocamera.",
    start_btn: "Avvia scansione",
    title: "Guarda dritto verso la fotocamera",
  },
  processing: "Elaborazione in corso...",
  sdk_aria: "Acquisisci il volto",
} as const;
