/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ja. Generated by core-i18n. */
export default {
  close: "閉じる",
  error_dialogs: {
    cancel_btn: "スキャンをキャンセル",
    check_internet_connection: {
      aria_description: "インターネットに接続してから、もう一度スキャンしてください。",
      title: "インターネット接続を確認してください",
    },
    network_error: {
      aria_description: "もう一度スキャンしてください。問題が続く場合は、キャンセルして後でもう一度お試しください。",
      title: "ネットワークエラー",
    },
    retry_btn: "再試行",
    scanning_not_available: {
      aria_description: "このダイアログを閉じて、後でもう一度お試しください。",
      title: "スキャンできません",
    },
    scanning_unsuccessful: {
      details: "顔を検出できません。もう一度お試しください。",
      title: "スキャンに失敗しました",
    },
  },
  feedback_messages: {
    angled_pitch: "カメラをまっすぐ見てください",
    angled_roll: "カメラをまっすぐ見てください",
    angled_yaw: "カメラをまっすぐ見てください",
    capture_complete_aria: "顔の撮影が完了しました",
    face_not_found: "顔を画面の中央に合わせてください",
    multiple_faces: "顔が1つだけ映るようにしてください",
    not_still: "動かないでください",
    ok: "そのまま動かないでください",
    too_blurry: "動かないでください",
    too_bright: "光がやわらかい場所に移動してください",
    too_close: "遠くへ移動",
    too_close_to_border: "顔を中央に合わせてください",
    too_dark: "明るい場所に移動してください",
    too_far: "近くへ移動",
  },
  help_button: {
    aria_label: "ヘルプ",
    tooltip: "ヘルプが必要ですか？",
  },
  help_modal: {
    aria: "顔撮影のヘルプ",
    back_btn: "戻る",
    done_btn: "完了",
    done_btn_aria: "顔撮影を再開",
    next_btn: "次へ",
    steps: {
      camera_lens: {
        details: "カメラレンズに汚れやほこりがないか確認してください。レンズが汚れていると写真がぼやけ、顔を鮮明に撮影しにくくなります。",
        title: "カメラのレンズを拭いてください",
      },
      centered_face: {
        details: "カメラをまっすぐ見て、顔を画面の中央に合わせてください。デバイスをしっかり持ち、顔が撮影されるまで自然な表情で動かないでください。",
        title: "顔を中央に合わせてください",
      },
      lighting: {
        details: "顔がはっきり見えることを確認してください。暗すぎる場所や明るすぎる場所は避け、光源を背にせず、光源に向かってください。",
        title: "適切な明るさの場所を選んでください",
      },
      obstructions: {
        details: "顔が何かで覆われていないことを確認してください。サングラス、帽子、または目や顔の特徴を隠すものを外してください。",
        title: "顔を覆うものを外してください",
      },
    },
  },
  onboarding_modal: {
    aria: "顔撮影の手順",
    cancel_btn: "キャンセル",
    details: "動かずに、カメラ画面の中央に顔を合わせてください。",
    start_btn: "スキャンを開始",
    title: "カメラをまっすぐ見てください",
  },
  processing: "処理中…",
  sdk_aria: "顔を撮影",
} as const;
