/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ko. Generated by core-i18n. */
export default {
  close: "닫기",
  error_dialogs: {
    cancel_btn: "스캔 취소",
    check_internet_connection: {
      aria_description: "인터넷에 연결한 후 다시 스캔하세요.",
      title: "인터넷 연결 확인",
    },
    network_error: {
      aria_description: "스캔을 다시 시도하세요. 문제가 계속되면 취소하고 나중에 다시 시도하세요.",
      title: "네트워크 오류",
    },
    retry_btn: "다시 시도",
    scanning_not_available: {
      aria_description: "이 대화 상자를 닫고 나중에 다시 시도하세요.",
      title: "스캔할 수 없음",
    },
    scanning_unsuccessful: {
      details: "얼굴을 감지할 수 없습니다. 다시 시도하세요.",
      title: "스캔 실패",
    },
  },
  feedback_messages: {
    angled_pitch: "카메라를 정면으로 바라보세요",
    angled_roll: "카메라를 정면으로 바라보세요",
    angled_yaw: "카메라를 정면으로 바라보세요",
    capture_complete_aria: "성공! 얼굴이 캡처되었습니다",
    face_not_found: "화면 중앙에 얼굴을 맞추세요",
    multiple_faces: "한 사람의 얼굴만 보이게 하세요",
    not_still: "움직이지 마세요",
    ok: "좋습니다! 움직이지 마세요",
    too_blurry: "움직이지 마세요",
    too_bright: "조명이 더 부드러운 곳으로 이동하세요",
    too_close: "더 멀리 이동",
    too_close_to_border: "얼굴을 중앙에 맞추세요",
    too_dark: "더 밝은 곳으로 이동하세요",
    too_far: "더 가까이 이동",
  },
  help_button: {
    aria_label: "도움말",
    tooltip: "도움이 필요하신가요?",
  },
  help_modal: {
    aria: "얼굴 캡처 도움말",
    back_btn: "뒤로",
    done_btn: "완료",
    done_btn_aria: "얼굴 캡처 계속하기",
    next_btn: "다음",
    steps: {
      camera_lens: {
        details: "카메라 렌즈에 얼룩이나 먼지가 있는지 확인하세요. 렌즈가 더러우면 사진이 흐려져 시스템이 얼굴을 선명하게 캡처하기 어려울 수 있습니다.",
        title: "카메라 렌즈를 닦아 주세요",
      },
      centered_face: {
        details: "카메라를 똑바로 보고 화면 중앙에 얼굴을 맞추세요. 얼굴이 캡처될 때까지 기기를 안정적으로 잡고 무표정을 유지하세요.",
        title: "얼굴을 중앙에 맞추세요",
      },
      lighting: {
        details: "얼굴이 선명하게 보이도록 하세요. 너무 어둡거나 밝은 조명은 피하고, 광원을 등지지 말고 광원을 향하세요.",
        title: "적절한 조명을 찾으세요",
      },
      obstructions: {
        details: "얼굴을 가리는 것이 없는지 확인하세요. 선글라스, 모자 또는 눈이나 얼굴 특징을 가리는 물건을 제거하세요.",
        title: "얼굴을 가리는 물건을 제거하세요",
      },
    },
  },
  onboarding_modal: {
    aria: "얼굴 캡처 안내",
    cancel_btn: "취소",
    details: "움직이지 말고 카메라 화면 중앙에 얼굴을 맞추세요.",
    start_btn: "스캔 시작",
    title: "카메라를 정면으로 바라보세요",
  },
  processing: "처리 중...",
  sdk_aria: "얼굴을 캡처하세요",
} as const;
