/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for lv. Generated by core-i18n. */
export default {
  close: "Aizvērt",
  error_dialogs: {
    cancel_btn: "Atcelt skenēšanu",
    check_internet_connection: {
      aria_description: "Izveidojiet savienojumu ar internetu un pēc tam mēģiniet skenēt vēlreiz.",
      title: "Pārbaudiet interneta savienojumu",
    },
    network_error: {
      aria_description: "Mēģiniet skenēt vēlreiz. Ja problēma joprojām pastāv, atceliet un mēģiniet vēlreiz vēlāk.",
      title: "Tīkla kļūda",
    },
    retry_btn: "Mēģināt no jauna",
    scanning_not_available: {
      aria_description: "Aizveriet šo dialoglodziņu un mēģiniet vēlreiz vēlāk.",
      title: "Skenēšana nav pieejama",
    },
    scanning_unsuccessful: {
      details: "Neizdevās noteikt jūsu seju. Mēģiniet vēlreiz.",
      title: "Skenēšana neizdevās",
    },
  },
  feedback_messages: {
    angled_pitch: "Skatieties tieši kamerā",
    angled_roll: "Skatieties tieši kamerā",
    angled_yaw: "Skatieties tieši kamerā",
    capture_complete_aria: "Izdevās! Seja ir uzņemta",
    face_not_found: "Novietojiet seju ekrāna centrā",
    multiple_faces: "Kadrā jābūt redzamai tikai vienai sejai",
    not_still: "Nekustieties",
    ok: "Lieliski! Nekustieties",
    too_blurry: "Nekustieties",
    too_bright: "Pārejiet uz vietu ar maigāku apgaismojumu",
    too_close: "Pārvietot tālāk",
    too_close_to_border: "Novietojiet seju centrā",
    too_dark: "Pārejiet uz gaišāku vietu",
    too_far: "Pārvietot tuvāk",
  },
  help_button: {
    aria_label: "Palīdzība",
    tooltip: "Vai vajadzīga palīdzība?",
  },
  help_modal: {
    aria: "Palīdzība par sejas uzņemšanu",
    back_btn: "Atpakaļ",
    done_btn: "Gatavs",
    done_btn_aria: "Atsākt sejas uzņemšanu",
    next_btn: "Nākamais",
    steps: {
      camera_lens: {
        details: "Pārbaudiet, vai uz kameras objektīva nav traipu vai putekļu. Netīrs objektīvs var padarīt fotoattēlu izplūdušu un apgrūtināt sistēmai skaidru jūsu sejas uzņemšanu.",
        title: "Notīriet kameras objektīvu",
      },
      centered_face: {
        details: "Skatieties tieši kamerā un novietojiet seju ekrāna centrā. Turiet ierīci nekustīgi un saglabājiet neitrālu sejas izteiksmi, līdz seja ir uzņemta.",
        title: "Turiet seju centrā",
      },
      lighting: {
        details: "Pārliecinieties, ka seja ir skaidri redzama. Izvairieties no ļoti tumša vai ļoti spilgta apgaismojuma un pavērsiet seju pret gaismas avotu, nevis turiet to aiz sevis.",
        title: "Atrodiet labu apgaismojumu",
      },
      obstructions: {
        details: "Pārliecinieties, ka jūsu seju nekas neaizsedz. Noņemiet saulesbrilles, cepuri vai jebko citu, kas aizsedz acis vai sejas vaibstus.",
        title: "Noņemiet aizsedzošus priekšmetus",
      },
    },
  },
  onboarding_modal: {
    aria: "Sejas uzņemšanas norādījumi",
    cancel_btn: "Atcelt",
    details: "Nekustieties un novietojiet seju kameras ekrāna centrā.",
    start_btn: "Sāciet skenēšanu",
    title: "Skatieties tieši kamerā",
  },
  processing: "Apstrāde...",
  sdk_aria: "Uzņemiet savas sejas attēlu",
} as const;
