/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ms. Generated by core-i18n. */
export default {
  close: "Tutup",
  error_dialogs: {
    cancel_btn: "Batalkan pengimbasan",
    check_internet_connection: {
      aria_description: "Sambungkan ke internet, kemudian cuba imbas semula.",
      title: "Semak sambungan internet",
    },
    network_error: {
      aria_description: "Cuba imbas semula. Jika masalah berterusan, batalkan dan cuba lagi kemudian.",
      title: "Ralat rangkaian",
    },
    retry_btn: "Cuba semula",
    scanning_not_available: {
      aria_description: "Tutup dialog ini dan cuba lagi kemudian.",
      title: "Pengimbasan tidak tersedia",
    },
    scanning_unsuccessful: {
      details: "Wajah anda tidak dapat dikesan. Sila cuba lagi.",
      title: "Pengimbasan tidak berjaya",
    },
  },
  feedback_messages: {
    angled_pitch: "Pandang terus ke kamera",
    angled_roll: "Pandang terus ke kamera",
    angled_yaw: "Pandang terus ke kamera",
    capture_complete_aria: "Berjaya! Wajah ditangkap",
    face_not_found: "Letakkan wajah anda di tengah skrin",
    multiple_faces: "Pastikan hanya satu wajah kelihatan",
    not_still: "Jangan bergerak",
    ok: "Bagus! Jangan bergerak",
    too_blurry: "Jangan bergerak",
    too_bright: "Bergerak ke tempat dengan pencahayaan yang lebih lembut",
    too_close: "Jauhkan lagi",
    too_close_to_border: "Letakkan wajah anda di tengah",
    too_dark: "Bergerak ke tempat yang lebih terang",
    too_far: "Dekatkan lagi",
  },
  help_button: {
    aria_label: "Bantuan",
    tooltip: "Perlukan bantuan?",
  },
  help_modal: {
    aria: "Bantuan tangkapan wajah",
    back_btn: "Kembali",
    done_btn: "Siap",
    done_btn_aria: "Teruskan tangkapan wajah",
    next_btn: "Seterusnya",
    steps: {
      camera_lens: {
        details: "Periksa kanta kamera anda untuk kesan kotoran atau habuk. Kanta yang kotor boleh menyebabkan foto anda kabur dan menyukarkan sistem menangkap wajah anda dengan jelas.",
        title: "Bersihkan lensa kamera anda",
      },
      centered_face: {
        details: "Pandang terus ke kamera dan letakkan wajah anda di tengah skrin. Pegang peranti anda dengan stabil dan kekalkan ekspresi neutral sehingga wajah anda ditangkap.",
        title: "Pastikan wajah anda di tengah",
      },
      lighting: {
        details: "Pastikan wajah anda kelihatan dengan jelas. Elakkan pencahayaan yang terlalu gelap atau terlalu terang, dan hadapkan wajah anda ke arah sumber cahaya, bukan membelakanginya.",
        title: "Cari pencahayaan yang baik",
      },
      obstructions: {
        details: "Pastikan tiada apa-apa yang menutupi wajah anda. Tanggalkan cermin mata hitam, topi atau apa-apa yang menghalang mata atau ciri wajah anda.",
        title: "Tanggalkan halangan",
      },
    },
  },
  onboarding_modal: {
    aria: "Arahan tangkapan wajah",
    cancel_btn: "Batal",
    details: "Pastikan anda tidak bergerak dan letakkan wajah anda di tengah-tengah paparan kamera.",
    start_btn: "Mula Mengimbas",
    title: "Pandang terus ke kamera",
  },
  processing: "Memproses...",
  sdk_aria: "Tangkap wajah anda",
} as const;
