/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for nl. Generated by core-i18n. */
export default {
  close: "Sluiten",
  error_dialogs: {
    cancel_btn: "Scannen annuleren",
    check_internet_connection: {
      aria_description: "Maak verbinding met internet en probeer daarna opnieuw te scannen.",
      title: "Controleer je internetverbinding",
    },
    network_error: {
      aria_description: "Probeer opnieuw te scannen. Annuleer en probeer het later opnieuw als het probleem aanhoudt.",
      title: "Netwerkfout",
    },
    retry_btn: "Probeer opnieuw",
    scanning_not_available: {
      aria_description: "Sluit dit dialoogvenster en probeer het later opnieuw.",
      title: "Scannen niet beschikbaar",
    },
    scanning_unsuccessful: {
      details: "Je gezicht kon niet worden gedetecteerd. Probeer het opnieuw.",
      title: "Scannen mislukt",
    },
  },
  feedback_messages: {
    angled_pitch: "Kijk recht in de camera",
    angled_roll: "Kijk recht in de camera",
    angled_yaw: "Kijk recht in de camera",
    capture_complete_aria: "Gelukt! Gezicht vastgelegd",
    face_not_found: "Centreer je gezicht op het scherm",
    multiple_faces: "Zorg dat er slechts één gezicht zichtbaar is",
    not_still: "Blijf stil",
    ok: "Perfect! Blijf stil",
    too_blurry: "Blijf stil",
    too_bright: "Ga naar een plek met zachter licht",
    too_close: "Beweeg verder weg",
    too_close_to_border: "Centreer je gezicht",
    too_dark: "Ga naar een lichtere plek",
    too_far: "Beweeg dichterbij",
  },
  help_button: {
    aria_label: "Help",
    tooltip: "Hulp nodig?",
  },
  help_modal: {
    aria: "Hulp bij gezichtsopname",
    back_btn: "Terug",
    done_btn: "Gereed",
    done_btn_aria: "Gezichtsopname hervatten",
    next_btn: "Volgende",
    steps: {
      camera_lens: {
        details: "Controleer je cameralens op vegen of stof. Een vuile lens kan je foto wazig maken, waardoor het systeem je gezicht minder goed kan vastleggen.",
        title: "Maak de lens van uw camera schoon",
      },
      centered_face: {
        details: "Kijk recht in de camera en centreer je gezicht op het scherm. Houd je apparaat stil en houd een neutrale gezichtsuitdrukking totdat je gezicht is vastgelegd.",
        title: "Houd je gezicht gecentreerd",
      },
      lighting: {
        details: "Zorg dat je gezicht duidelijk zichtbaar is. Vermijd te weinig of te fel licht en ga met je gezicht naar de lichtbron staan in plaats van met je rug ernaartoe.",
        title: "Zorg voor goede verlichting",
      },
      obstructions: {
        details: "Zorg dat niets je gezicht bedekt. Doe zonnebrillen en hoeden af en verwijder alles wat je ogen of gezichtskenmerken bedekt.",
        title: "Verwijder alles wat je gezicht bedekt",
      },
    },
  },
  onboarding_modal: {
    aria: "Instructies voor gezichtsopname",
    cancel_btn: "Annuleren",
    details: "Blijf stil en houd uw gezicht in het midden van het camerabeeld.",
    start_btn: "Beginnen met scannen",
    title: "Kijk recht in de camera",
  },
  processing: "Verwerken...",
  sdk_aria: "Uw gezicht opnemen",
} as const;
