/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for no. Generated by core-i18n. */
export default {
  close: "Lukk",
  error_dialogs: {
    cancel_btn: "Avbryt skanning",
    check_internet_connection: {
      aria_description: "Koble til internett, og prøv deretter å skanne på nytt.",
      title: "Kontroller internettforbindelsen",
    },
    network_error: {
      aria_description: "Prøv å skanne på nytt. Hvis problemet vedvarer, avbryt og prøv igjen senere.",
      title: "Nettverksfeil",
    },
    retry_btn: "Prøv på nytt",
    scanning_not_available: {
      aria_description: "Lukk denne dialogboksen, og prøv igjen senere.",
      title: "Skanning er ikke tilgjengelig",
    },
    scanning_unsuccessful: {
      details: "Ansiktet ditt ble ikke oppdaget. Prøv igjen.",
      title: "Skanningen mislyktes",
    },
  },
  feedback_messages: {
    angled_pitch: "Se rett inn i kameraet",
    angled_roll: "Se rett inn i kameraet",
    angled_yaw: "Se rett inn i kameraet",
    capture_complete_aria: "Vellykket! Bildet av ansiktet er tatt",
    face_not_found: "Plasser ansiktet midt på skjermen",
    multiple_faces: "Bare ett ansikt skal være synlig",
    not_still: "Hold deg i ro",
    ok: "Perfekt! Hold deg i ro",
    too_blurry: "Hold deg i ro",
    too_bright: "Flytt til et sted med mykere lys",
    too_close: "Flytt lenger bort",
    too_close_to_border: "Plasser ansiktet midt på skjermen",
    too_dark: "Flytt til et lysere sted",
    too_far: "Flytt nærmere",
  },
  help_button: {
    aria_label: "Hjelp",
    tooltip: "Trenger du hjelp?",
  },
  help_modal: {
    aria: "Hjelp med ansiktsskanning",
    back_btn: "Tilbake",
    done_btn: "Ferdig",
    done_btn_aria: "Fortsett ansiktsopptaket",
    next_btn: "Neste",
    steps: {
      camera_lens: {
        details: "Kontroller kameralinsen for flekker eller støv. En skitten linse kan gjøre bildet uskarpt og gjøre det vanskeligere for systemet å ta et tydelig bilde av ansiktet ditt.",
        title: "Rens kameralinsen din",
      },
      centered_face: {
        details: "Se rett på kameraet, og plasser ansiktet midt på skjermen. Hold enheten stødig og ha et nøytralt ansiktsuttrykk til bildet av ansiktet ditt er tatt.",
        title: "Hold ansiktet midt på skjermen",
      },
      lighting: {
        details: "Sørg for at ansiktet ditt er tydelig synlig. Unngå svært mørk eller svært sterk belysning, og vend ansiktet mot lyskilden i stedet for å ha den bak deg.",
        title: "Finn god belysning",
      },
      obstructions: {
        details: "Sørg for at ingenting dekker ansiktet ditt. Ta av solbriller, hatter eller annet som dekker øynene eller ansiktstrekkene dine.",
        title: "Fjern hindringer",
      },
    },
  },
  onboarding_modal: {
    aria: "Instruksjoner for ansiktsopptak",
    cancel_btn: "Avbryt",
    details: "Hold deg i ro, og plasser ansiktet midt i kamerabildet.",
    start_btn: "Start skanning",
    title: "Se rett inn i kameraet",
  },
  processing: "Behandler ...",
  sdk_aria: "Ta bilde av ansiktet ditt",
} as const;
