/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for pl. Generated by core-i18n. */
export default {
  close: "Zamknij",
  error_dialogs: {
    cancel_btn: "Anuluj skanowanie",
    check_internet_connection: {
      aria_description: "Połącz się z internetem, a następnie spróbuj zeskanować twarz ponownie.",
      title: "Sprawdź połączenie z internetem",
    },
    network_error: {
      aria_description: "Spróbuj zeskanować twarz ponownie. Jeśli problem będzie się powtarzał, anuluj i spróbuj później.",
      title: "Błąd sieci",
    },
    retry_btn: "Spróbuj ponownie",
    scanning_not_available: {
      aria_description: "Zamknij to okno dialogowe i spróbuj ponownie później.",
      title: "Skanowanie jest niedostępne",
    },
    scanning_unsuccessful: {
      details: "Nie wykryto twarzy. Spróbuj ponownie.",
      title: "Skanowanie nie powiodło się",
    },
  },
  feedback_messages: {
    angled_pitch: "Patrz prosto w kamerę",
    angled_roll: "Patrz prosto w kamerę",
    angled_yaw: "Patrz prosto w kamerę",
    capture_complete_aria: "Sukces! Zarejestrowano twarz",
    face_not_found: "Umieść twarz na środku ekranu",
    multiple_faces: "W kadrze powinna być widoczna tylko jedna twarz",
    not_still: "Nie ruszaj się",
    ok: "Doskonale! Nie ruszaj się",
    too_blurry: "Nie ruszaj się",
    too_bright: "Przejdź w miejsce z łagodniejszym oświetleniem",
    too_close: "Przesuń dalej",
    too_close_to_border: "Umieść twarz na środku",
    too_dark: "Przejdź w jaśniejsze miejsce",
    too_far: "Przesuń bliżej",
  },
  help_button: {
    aria_label: "Pomoc",
    tooltip: "Potrzebujesz pomocy?",
  },
  help_modal: {
    aria: "Pomoc dotycząca rejestrowania twarzy",
    back_btn: "Wstecz",
    done_btn: "Gotowe",
    done_btn_aria: "Wznów rejestrowanie twarzy",
    next_btn: "Dalej",
    steps: {
      camera_lens: {
        details: "Sprawdź, czy na obiektywie aparatu nie ma smug ani kurzu. Brudny obiektyw może rozmazać obraz i utrudnić wyraźne zarejestrowanie twarzy.",
        title: "Wyczyść obiektyw aparatu",
      },
      centered_face: {
        details: "Patrz prosto w aparat i umieść twarz na środku ekranu. Trzymaj urządzenie nieruchomo i zachowaj neutralny wyraz twarzy, aż twarz zostanie zarejestrowana.",
        title: "Trzymaj twarz na środku",
      },
      lighting: {
        details: "Upewnij się, że twarz jest wyraźnie widoczna. Unikaj zbyt słabego lub zbyt intensywnego oświetlenia. Skieruj twarz w stronę źródła światła, zamiast ustawiać je za sobą.",
        title: "Znajdź dobre oświetlenie",
      },
      obstructions: {
        details: "Upewnij się, że nic nie zasłania twarzy. Zdejmij okulary przeciwsłoneczne, nakrycie głowy lub inne rzeczy zasłaniające oczy albo rysy twarzy.",
        title: "Usuń przeszkody",
      },
    },
  },
  onboarding_modal: {
    aria: "Instrukcje dotyczące rejestrowania twarzy",
    cancel_btn: "Anuluj",
    details: "Nie ruszaj się i ustaw twarz na środku kadru.",
    start_btn: "Rozpocznij skanowanie",
    title: "Patrz prosto w kamerę",
  },
  processing: "Przetwarzanie...",
  sdk_aria: "Zarejestruj swoją twarz",
} as const;
