/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ps_AF. Generated by core-i18n. */
export default {
  close: "تړل",
  error_dialogs: {
    cancel_btn: "سکن کول لغوه کړئ",
    check_internet_connection: {
      aria_description: "له انټرنېټ سره وصل شئ، بیا د سکن کولو هڅه وکړئ.",
      title: "د انټرنېټ اړیکه وګورئ",
    },
    network_error: {
      aria_description: "د سکن کولو هڅه بیا وکړئ. که ستونزه دوام وکړي، لغوه یې کړئ او وروسته بیا هڅه وکړئ.",
      title: "د شبکې تېروتنه",
    },
    retry_btn: "بیا هڅه وکړئ",
    scanning_not_available: {
      aria_description: "دا ډیالوګ بند کړئ او وروسته بیا هڅه وکړئ.",
      title: "سکن کول ممکن نه دي",
    },
    scanning_unsuccessful: {
      details: "ستاسو مخ ونه موندل شو. مهرباني وکړئ بیا هڅه وکړئ.",
      title: "سکن بریالی نه شو",
    },
  },
  feedback_messages: {
    angled_pitch: "نېغ کامرې ته وګورئ",
    angled_roll: "نېغ کامرې ته وګورئ",
    angled_yaw: "نېغ کامرې ته وګورئ",
    capture_complete_aria: "بریا! مخ مو ثبت شو",
    face_not_found: "خپل مخ د سکرین په منځ کې ونیسئ",
    multiple_faces: "ډاډ ترلاسه کړئ چې یوازې یو مخ ښکاره وي",
    not_still: "بې‌حرکته پاتې شئ",
    ok: "ښه! بې‌حرکته پاتې شئ",
    too_blurry: "بې‌حرکته پاتې شئ",
    too_bright: "داسې ځای ته لاړ شئ چې رڼا یې نرمه وي",
    too_close: "نور لاړ شه",
    too_close_to_border: "خپل مخ په منځ کې ونیسئ",
    too_dark: "روښانه ځای ته لاړ شئ",
    too_far: "نږدې شه",
  },
  help_button: {
    aria_label: "مرسته",
    tooltip: "تاسو مرستې ته اړتیا لرئ؟",
  },
  help_modal: {
    aria: "د مخ ثبتولو مرسته",
    back_btn: "شاته",
    done_btn: "وشو",
    done_btn_aria: "د مخ نیول بېرته پیل کړئ",
    next_btn: "بل",
    steps: {
      camera_lens: {
        details: "وګورئ چې د کامرې پر لینز مو داغونه یا دوړې نه وي. چټل لینز ستاسو انځور تتولای شي او سیستم ته ستاسو د مخ په روښانه ثبتولو کې ستونزه جوړولای شي.",
        title: "خپل د کمرې لینز پاک کړئ",
      },
      centered_face: {
        details: "نېغ د کامرې لور ته وګورئ او خپل مخ د سکرین په منځ کې ونیسئ. وسیله مو ثابته ونیسئ او تر هغه چې مخ مو ثبتېږي، د مخ حالت مو عادي وساتئ.",
        title: "خپل مخ په منځ کې وساتئ",
      },
      lighting: {
        details: "ډاډ ترلاسه کړئ چې مخ مو په روښانه ډول ښکاري. له ډېرې تیارې یا ډېرې روښانه رڼا څخه ډډه وکړئ، او د رڼا سرچینې ته مخامخ شئ، نه دا چې رڼا مو شاته وي.",
        title: "مناسبه رڼا ومومئ",
      },
      obstructions: {
        details: "ډاډ ترلاسه کړئ چې هېڅ شی مو مخ نه پټوي. لمرینې عینکې، خولۍ، یا هر هغه څه لرې کړئ چې سترګې یا د مخ ځانګړنې مو پټوي.",
        title: "خنډونه لرې کړئ",
      },
    },
  },
  onboarding_modal: {
    aria: "د مخ نیولو لارښوونې",
    cancel_btn: "لغوه کړئ",
    details: "بې‌حرکته پاتې شئ او خپل مخ د کامرې د پردې په منځ کې راوړئ.",
    start_btn: "سکن کول پیل کړئ",
    title: "نېغ کامرې ته وګورئ",
  },
  processing: "پروسس کېږي...",
  sdk_aria: "خپل مخ ونیسئ",
} as const;
