/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for pt. Generated by core-i18n. */
export default {
  close: "Fechar",
  error_dialogs: {
    cancel_btn: "Cancelar a captura",
    check_internet_connection: {
      aria_description: "Ligue-se à Internet e tente novamente.",
      title: "Verifique a ligação à Internet",
    },
    network_error: {
      aria_description: "Tente novamente. Se o problema persistir, cancele e tente mais tarde.",
      title: "Erro de rede",
    },
    retry_btn: "Tente novamente",
    scanning_not_available: {
      aria_description: "Feche esta caixa de diálogo e tente novamente mais tarde.",
      title: "Captura indisponível",
    },
    scanning_unsuccessful: {
      details: "Não foi possível detetar o seu rosto. Tente novamente.",
      title: "Captura sem sucesso",
    },
  },
  feedback_messages: {
    angled_pitch: "Olhe diretamente para a câmara",
    angled_roll: "Olhe diretamente para a câmara",
    angled_yaw: "Olhe diretamente para a câmara",
    capture_complete_aria: "Sucesso! Rosto capturado",
    face_not_found: "Centre o rosto no ecrã",
    multiple_faces: "Deixe apenas um rosto visível",
    not_still: "Mantenha-se imóvel",
    ok: "Perfeito! Mantenha-se imóvel",
    too_blurry: "Mantenha-se imóvel",
    too_bright: "Vá para um local com luz mais suave",
    too_close: "Afaste",
    too_close_to_border: "Centre o rosto",
    too_dark: "Vá para um local mais iluminado",
    too_far: "Aproxime",
  },
  help_button: {
    aria_label: "Ajuda",
    tooltip: "Precisa de ajuda?",
  },
  help_modal: {
    aria: "Ajuda para a captura facial",
    back_btn: "Anterior",
    done_btn: "Concluído",
    done_btn_aria: "Retomar a captura facial",
    next_btn: "Seguinte",
    steps: {
      camera_lens: {
        details: "Verifique se a lente da câmara tem manchas ou pó. Uma lente suja pode desfocar a sua imagem e dificultar a captura nítida do seu rosto.",
        title: "Limpe a lente da câmara",
      },
      centered_face: {
        details: "Olhe diretamente para a câmara e centre o rosto no ecrã. Mantenha o dispositivo firme e uma expressão neutra até o rosto ser capturado.",
        title: "Mantenha o rosto centrado",
      },
      lighting: {
        details: "Certifique-se de que o seu rosto está claramente visível. Evite luz muito fraca ou muito intensa e fique de frente para a fonte de luz, em vez de a ter atrás de si.",
        title: "Encontre um local bem iluminado",
      },
      obstructions: {
        details: "Certifique-se de que nada cobre o seu rosto. Retire óculos de sol, chapéus ou qualquer objeto que tape os olhos ou os traços faciais.",
        title: "Remova obstruções",
      },
    },
  },
  onboarding_modal: {
    aria: "Instruções de captura facial",
    cancel_btn: "Cancelar",
    details: "Mantenha-se imóvel e centre o rosto no ecrã da câmara.",
    start_btn: "Começar a digitalizar",
    title: "Olhe diretamente para a câmara",
  },
  processing: "A processar...",
  sdk_aria: "Capture o seu rosto",
} as const;
