/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for pt_BR. Generated by core-i18n. */
export default {
  close: "Fechar",
  error_dialogs: {
    cancel_btn: "Cancelar captura",
    check_internet_connection: {
      aria_description: "Conecte-se à internet e tente capturar novamente.",
      title: "Verifique a conexão com a internet",
    },
    network_error: {
      aria_description: "Tente capturar novamente. Se o problema persistir, cancele e tente mais tarde.",
      title: "Erro de rede",
    },
    retry_btn: "Tentar novamente",
    scanning_not_available: {
      aria_description: "Feche esta caixa de diálogo e tente novamente mais tarde.",
      title: "Captura indisponível",
    },
    scanning_unsuccessful: {
      details: "Não foi possível detectar seu rosto. Tente novamente.",
      title: "Não foi possível concluir a captura",
    },
  },
  feedback_messages: {
    angled_pitch: "Olhe diretamente para a câmera",
    angled_roll: "Olhe diretamente para a câmera",
    angled_yaw: "Olhe diretamente para a câmera",
    capture_complete_aria: "Sucesso! Rosto capturado",
    face_not_found: "Centralize seu rosto na tela",
    multiple_faces: "Apenas um rosto deve estar visível",
    not_still: "Fique imóvel",
    ok: "Perfeito! Fique imóvel",
    too_blurry: "Fique imóvel",
    too_bright: "Vá para um local com iluminação mais suave",
    too_close: "Afaste",
    too_close_to_border: "Centralize seu rosto",
    too_dark: "Vá para um local mais iluminado",
    too_far: "Aproxime",
  },
  help_button: {
    aria_label: "Ajuda",
    tooltip: "Precisa de ajuda?",
  },
  help_modal: {
    aria: "Ajuda para captura de rosto",
    back_btn: "Voltar",
    done_btn: "Concluído",
    done_btn_aria: "Retomar a captura facial",
    next_btn: "Próximo",
    steps: {
      camera_lens: {
        details: "Verifique se há manchas ou poeira na lente da câmera. Uma lente suja pode deixar sua foto desfocada e dificultar a captura nítida do seu rosto pelo sistema.",
        title: "Limpe a lente da câmera",
      },
      centered_face: {
        details: "Olhe diretamente para a câmera e centralize seu rosto na tela. Mantenha o dispositivo firme e uma expressão neutra até que seu rosto seja capturado.",
        title: "Mantenha seu rosto centralizado",
      },
      lighting: {
        details: "Certifique-se de que seu rosto esteja bem visível. Evite ambientes muito escuros ou muito claros e fique de frente para a fonte de luz, em vez de deixá-la atrás de você.",
        title: "Encontre um local bem iluminado",
      },
      obstructions: {
        details: "Certifique-se de que nada esteja cobrindo seu rosto. Remova óculos de sol, chapéus ou qualquer item que cubra seus olhos ou traços faciais.",
        title: "Remova obstruções",
      },
    },
  },
  onboarding_modal: {
    aria: "Instruções para captura facial",
    cancel_btn: "Cancelar",
    details: "Fique parado e centralize seu rosto na tela da câmera.",
    start_btn: "Iniciar escaneamento",
    title: "Olhe diretamente para a câmera",
  },
  processing: "Processando...",
  sdk_aria: "Capture seu rosto",
} as const;
