/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ro. Generated by core-i18n. */
export default {
  close: "Închide",
  error_dialogs: {
    cancel_btn: "Anulați scanarea",
    check_internet_connection: {
      aria_description: "Conectați-vă la internet, apoi reîncercați scanarea.",
      title: "Verificați conexiunea la internet",
    },
    network_error: {
      aria_description: "Reîncercați scanarea. Dacă problema persistă, anulați și încercați din nou mai târziu.",
      title: "Eroare de rețea",
    },
    retry_btn: "Reîncercare",
    scanning_not_available: {
      aria_description: "Închideți această casetă de dialog și încercați din nou mai târziu.",
      title: "Scanarea nu este disponibilă",
    },
    scanning_unsuccessful: {
      details: "Fața nu a putut fi detectată. Încercați din nou.",
      title: "Scanare nereușită",
    },
  },
  feedback_messages: {
    angled_pitch: "Priviți direct în cameră",
    angled_roll: "Priviți direct în cameră",
    angled_yaw: "Priviți direct în cameră",
    capture_complete_aria: "Succes! Fața a fost capturată",
    face_not_found: "Centrați-vă fața pe ecran",
    multiple_faces: "Trebuie să fie vizibilă o singură față",
    not_still: "Nu vă mișcați",
    ok: "Perfect! Nu vă mișcați",
    too_blurry: "Nu vă mișcați",
    too_bright: "Mutați-vă într-un loc cu lumină mai blândă",
    too_close: "Îndepărtați",
    too_close_to_border: "Centrați-vă fața",
    too_dark: "Mutați-vă într-un loc mai luminos",
    too_far: "Apropiați",
  },
  help_button: {
    aria_label: "Ajutor",
    tooltip: "Aveți nevoie de ajutor?",
  },
  help_modal: {
    aria: "Ajutor pentru capturarea feței",
    back_btn: "Înapoi",
    done_btn: "Terminat",
    done_btn_aria: "Reluați capturarea feței",
    next_btn: "Următorul",
    steps: {
      camera_lens: {
        details: "Verificați dacă obiectivul camerei are pete sau praf. Un obiectiv murdar poate face fotografia neclară și poate îngreuna capturarea unei imagini clare a feței.",
        title: "Curățați lentila camerei",
      },
      centered_face: {
        details: "Priviți direct spre cameră și centrați-vă fața pe ecran. Țineți dispozitivul nemișcat și păstrați o expresie neutră până când fața este capturată.",
        title: "Mențineți fața centrată",
      },
      lighting: {
        details: "Asigurați-vă că fața este clar vizibilă. Evitați lumina foarte slabă sau foarte puternică și stați cu fața spre sursa de lumină, nu cu aceasta în spate.",
        title: "Găsiți o lumină bună",
      },
      obstructions: {
        details: "Asigurați-vă că nimic nu vă acoperă fața. Scoateți ochelarii de soare, pălăriile sau orice altceva care vă acoperă ochii ori trăsăturile feței.",
        title: "Îndepărtați obiectele care vă acoperă fața",
      },
    },
  },
  onboarding_modal: {
    aria: "Instrucțiuni pentru capturarea feței",
    cancel_btn: "Anulați",
    details: "Stați nemișcat și poziționați-vă fața în centrul ecranului camerei.",
    start_btn: "Porniți scanarea",
    title: "Priviți direct în cameră",
  },
  processing: "Se procesează...",
  sdk_aria: "Capturați-vă fața",
} as const;
