/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for sk. Generated by core-i18n. */
export default {
  close: "Zavrieť",
  error_dialogs: {
    cancel_btn: "Zrušiť skenovanie",
    check_internet_connection: {
      aria_description: "Pripojte sa na internet a potom skúste skenovanie znova.",
      title: "Skontrolujte internetové pripojenie",
    },
    network_error: {
      aria_description: "Skúste skenovanie znova. Ak problém pretrváva, zrušte ho a skúste to neskôr.",
      title: "Chyba siete",
    },
    retry_btn: "Skúsiť znova",
    scanning_not_available: {
      aria_description: "Zavrite toto dialógové okno a skúste to neskôr.",
      title: "Skenovanie nie je k dispozícii",
    },
    scanning_unsuccessful: {
      details: "Tvár sa nepodarilo rozpoznať. Skúste to znova.",
      title: "Skenovanie nebolo úspešné",
    },
  },
  feedback_messages: {
    angled_pitch: "Pozerajte sa priamo do fotoaparátu",
    angled_roll: "Pozerajte sa priamo do fotoaparátu",
    angled_yaw: "Pozerajte sa priamo do fotoaparátu",
    capture_complete_aria: "Tvár bola úspešne zachytená",
    face_not_found: "Umiestnite tvár do stredu obrazovky",
    multiple_faces: "V zábere nech je iba jedna tvár",
    not_still: "Nehýbte sa",
    ok: "Správne! Nehýbte sa",
    too_blurry: "Nehýbte sa",
    too_bright: "Presuňte sa na miesto s miernejším osvetlením",
    too_close: "Posuňte sa ďalej",
    too_close_to_border: "Umiestnite tvár do stredu",
    too_dark: "Presuňte sa na svetlejšie miesto",
    too_far: "Posuňte sa bližšie",
  },
  help_button: {
    aria_label: "Pomoc",
    tooltip: "Potrebujete pomoc?",
  },
  help_modal: {
    aria: "Pomoc pri snímaní tváre",
    back_btn: "Späť",
    done_btn: "Hotovo",
    done_btn_aria: "Pokračovať v snímaní tváre",
    next_btn: "Ďalej",
    steps: {
      camera_lens: {
        details: "Skontrolujte, či na objektíve kamery nie sú šmuhy alebo prach. Znečistený objektív môže rozmazať fotografiu a sťažiť systému zreteľné zachytenie vašej tváre.",
        title: "Vyčistite objektív kamery",
      },
      centered_face: {
        details: "Pozerajte sa priamo do kamery a umiestnite tvár do stredu obrazovky. Držte zariadenie pevne a zachovajte neutrálny výraz, kým nebude tvár zachytená.",
        title: "Držte tvár v strede",
      },
      lighting: {
        details: "Uistite sa, že je vaša tvár jasne viditeľná. Vyhnite sa veľmi tmavému alebo veľmi jasnému osvetleniu a otočte sa tvárou k zdroju svetla tak, aby nebol za vami.",
        title: "Nájdite vhodné osvetlenie",
      },
      obstructions: {
        details: "Uistite sa, že vašu tvár nič nezakrýva. Dajte dole slnečné okuliare, klobúk alebo čokoľvek, čo zakrýva oči alebo črty tváre.",
        title: "Odstráňte prekážky",
      },
    },
  },
  onboarding_modal: {
    aria: "Pokyny na snímanie tváre",
    cancel_btn: "Zrušiť",
    details: "Nehýbte sa a umiestnite tvár do stredu záberu.",
    start_btn: "Spustiť skenovanie",
    title: "Pozerajte sa priamo do fotoaparátu",
  },
  processing: "Spracovanie...",
  sdk_aria: "Nasnímajte svoju tvár",
} as const;
