/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for sl. Generated by core-i18n. */
export default {
  close: "Zapri",
  error_dialogs: {
    cancel_btn: "Prekliči skeniranje",
    check_internet_connection: {
      aria_description: "Povežite se z internetom, nato znova poskusite skenirati.",
      title: "Preverite internetno povezavo",
    },
    network_error: {
      aria_description: "Znova poskusite skenirati. Če se težava ponavlja, prekličite in poskusite znova pozneje.",
      title: "Omrežna napaka",
    },
    retry_btn: "Poskusi znova",
    scanning_not_available: {
      aria_description: "Zaprite to pogovorno okno in poskusite znova pozneje.",
      title: "Skeniranje ni na voljo",
    },
    scanning_unsuccessful: {
      details: "Vašega obraza ni bilo mogoče zaznati. Poskusite znova.",
      title: "Skeniranje ni uspelo",
    },
  },
  feedback_messages: {
    angled_pitch: "Glejte naravnost v kamero",
    angled_roll: "Glejte naravnost v kamero",
    angled_yaw: "Glejte naravnost v kamero",
    capture_complete_aria: "Uspešno! Obraz je zajet",
    face_not_found: "Postavite obraz na sredino zaslona",
    multiple_faces: "Viden naj bo samo en obraz",
    not_still: "Ostanite pri miru",
    ok: "Odlično! Ostanite pri miru",
    too_blurry: "Ostanite pri miru",
    too_bright: "Premaknite se na mesto z blažjo osvetlitvijo",
    too_close: "Oddaljite",
    too_close_to_border: "Postavite obraz na sredino",
    too_dark: "Premaknite se na svetlejše mesto",
    too_far: "Približajte",
  },
  help_button: {
    aria_label: "Pomoč",
    tooltip: "Potrebujete pomoč?",
  },
  help_modal: {
    aria: "Pomoč za zajem obraza",
    back_btn: "Nazaj",
    done_btn: "Končano",
    done_btn_aria: "Nadaljujte z zajemom obraza",
    next_btn: "Naprej",
    steps: {
      camera_lens: {
        details: "Preverite, ali so na objektivu kamere madeži ali prah. Umazan objektiv lahko zamegli fotografijo in sistemu oteži jasen zajem vašega obraza.",
        title: "Očistite objektiv kamere",
      },
      centered_face: {
        details: "Glejte naravnost v kamero in postavite obraz na sredino zaslona. Napravo držite pri miru in ohranite nevtralen izraz, dokler obraz ni zajet.",
        title: "Obraz naj bo na sredini",
      },
      lighting: {
        details: "Poskrbite, da je vaš obraz jasno viden. Izogibajte se zelo temni ali zelo močni svetlobi ter bodite obrnjeni proti viru svetlobe, ne pa tako, da je za vami.",
        title: "Poiščite dobro osvetlitev",
      },
      obstructions: {
        details: "Poskrbite, da nič ne prekriva vašega obraza. Odstranite sončna očala, pokrivala ali kar koli, kar zakriva oči ali obrazne poteze.",
        title: "Odstranite ovire",
      },
    },
  },
  onboarding_modal: {
    aria: "Navodila za zajem obraza",
    cancel_btn: "Prekliči",
    details: "Ostanite pri miru in obraz postavite na sredino zaslona.",
    start_btn: "Začetek skeniranja",
    title: "Glejte naravnost v kamero",
  },
  processing: "Obdelava ...",
  sdk_aria: "Zajemite obraz",
} as const;
