/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for sr. Generated by core-i18n. */
export default {
  close: "Zatvori",
  error_dialogs: {
    cancel_btn: "Otkaži skeniranje",
    check_internet_connection: {
      aria_description: "Povežite se na internet, a zatim pokušajte ponovo da skenirate.",
      title: "Proverite internet vezu",
    },
    network_error: {
      aria_description: "Pokušajte ponovo da skenirate. Ako se problem nastavi, otkažite i pokušajte ponovo kasnije.",
      title: "Greška mreže",
    },
    retry_btn: "Pokušaj ponovo",
    scanning_not_available: {
      aria_description: "Zatvorite ovaj dijalog i pokušajte ponovo kasnije.",
      title: "Skeniranje nije dostupno",
    },
    scanning_unsuccessful: {
      details: "Nije moguće prepoznati lice. Pokušajte ponovo.",
      title: "Skeniranje nije uspelo",
    },
  },
  feedback_messages: {
    angled_pitch: "Gledajte pravo u kameru",
    angled_roll: "Gledajte pravo u kameru",
    angled_yaw: "Gledajte pravo u kameru",
    capture_complete_aria: "Uspešno! Lice je snimljeno",
    face_not_found: "Postavite lice na sredinu ekrana",
    multiple_faces: "Treba da bude vidljivo samo jedno lice",
    not_still: "Mirujte",
    ok: "Odlično! Mirujte",
    too_blurry: "Mirujte",
    too_bright: "Pređite na mesto s blažim osvetljenjem",
    too_close: "Udaljite",
    too_close_to_border: "Postavite lice na sredinu",
    too_dark: "Pređite na svetlije mesto",
    too_far: "Približite",
  },
  help_button: {
    aria_label: "Pomoć",
    tooltip: "Potrebna vam je pomoć?",
  },
  help_modal: {
    aria: "Pomoć za snimanje lica",
    back_btn: "Nazad",
    done_btn: "Završeno",
    done_btn_aria: "Nastavite snimanje lica",
    next_btn: "Sledeći",
    steps: {
      camera_lens: {
        details: "Proverite da li na objektivu kamere ima mrlja ili prašine. Prljav objektiv može zamutiti fotografiju i otežati sistemu da jasno snimi vaše lice.",
        title: "Očistite sočiva kamere",
      },
      centered_face: {
        details: "Gledajte pravo u kameru i postavite lice na sredinu ekrana. Držite uređaj mirno i zadržite neutralan izraz lica dok se lice ne snimi.",
        title: "Držite lice na sredini",
      },
      lighting: {
        details: "Uverite se da vam je lice jasno vidljivo. Izbegavajte veoma tamno ili veoma jako osvetljenje i okrenite se ka izvoru svetlosti, umesto da vam bude iza leđa.",
        title: "Pronađite dobro osvetljeno mesto",
      },
      obstructions: {
        details: "Uverite se da vam ništa ne prekriva lice. Skinite naočare za sunce, kape ili bilo šta što zaklanja oči ili crte lica.",
        title: "Uklonite sve što prekriva lice",
      },
    },
  },
  onboarding_modal: {
    aria: "Uputstva za snimanje lica",
    cancel_btn: "Otkaži",
    details: "Mirujte i postavite lice u sredinu prikaza kamere.",
    start_btn: "Pokreni skeniranje",
    title: "Gledajte pravo u kameru",
  },
  processing: "Obrada...",
  sdk_aria: "Snimite lice",
} as const;
