/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for sv. Generated by core-i18n. */
export default {
  close: "Stäng",
  error_dialogs: {
    cancel_btn: "Avbryt skanningen",
    check_internet_connection: {
      aria_description: "Anslut till internet och försök sedan skanna igen.",
      title: "Kontrollera internetanslutningen",
    },
    network_error: {
      aria_description: "Försök skanna igen. Om problemet kvarstår, avbryt och försök igen senare.",
      title: "Nätverksfel",
    },
    retry_btn: "Försök igen",
    scanning_not_available: {
      aria_description: "Stäng den här dialogrutan och försök igen senare.",
      title: "Skanning är inte tillgänglig",
    },
    scanning_unsuccessful: {
      details: "Det gick inte att upptäcka ditt ansikte. Försök igen.",
      title: "Skanningen lyckades inte",
    },
  },
  feedback_messages: {
    angled_pitch: "Titta rakt in i kameran",
    angled_roll: "Titta rakt in i kameran",
    angled_yaw: "Titta rakt in i kameran",
    capture_complete_aria: "Klart! Bilden av ansiktet har tagits",
    face_not_found: "Centrera ansiktet på skärmen",
    multiple_faces: "Endast ett ansikte får vara synligt",
    not_still: "Håll dig stilla",
    ok: "Perfekt! Håll dig stilla",
    too_blurry: "Håll dig stilla",
    too_bright: "Flytta till en plats med mjukare ljus",
    too_close: "Flytta längre bort",
    too_close_to_border: "Centrera ansiktet",
    too_dark: "Flytta till en ljusare plats",
    too_far: "Flytta närmare",
  },
  help_button: {
    aria_label: "Hjälp",
    tooltip: "Behöver du hjälp?",
  },
  help_modal: {
    aria: "Hjälp med ansiktsfotografering",
    back_btn: "Tillbaka",
    done_btn: "Klart",
    done_btn_aria: "Fortsätt ansiktsfotograferingen",
    next_btn: "Nästa",
    steps: {
      camera_lens: {
        details: "Kontrollera om kameralinsen har fläckar eller damm. En smutsig lins kan göra bilden suddig och göra det svårare för systemet att fånga ditt ansikte tydligt.",
        title: "Rengör kameralinsen",
      },
      centered_face: {
        details: "Titta rakt in i kameran och centrera ansiktet på skärmen. Håll enheten stadigt och behåll ett neutralt ansiktsuttryck tills bilden har tagits.",
        title: "Håll ansiktet centrerat",
      },
      lighting: {
        details: "Se till att ansiktet syns tydligt. Undvik mycket svag eller stark belysning och vänd ansiktet mot ljuskällan i stället för att ha den bakom dig.",
        title: "Hitta bra ljus",
      },
      obstructions: {
        details: "Se till att inget täcker ansiktet. Ta av solglasögon, hattar eller annat som täcker ögonen eller ansiktsdragen.",
        title: "Ta bort sådant som täcker ansiktet",
      },
    },
  },
  onboarding_modal: {
    aria: "Instruktioner för ansiktsfotografering",
    cancel_btn: "Avbryt",
    details: "Håll dig stilla och centrera ansiktet i kamerabilden.",
    start_btn: "Börja skanna",
    title: "Titta rakt in i kameran",
  },
  processing: "Bearbetar...",
  sdk_aria: "Fotografera ditt ansikte",
} as const;
