/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for sw. Generated by core-i18n. */
export default {
  close: "Funga",
  error_dialogs: {
    cancel_btn: "Ghairi uchanganuzi",
    check_internet_connection: {
      aria_description: "Unganisha kwenye intaneti, kisha ujaribu kuchanganua tena.",
      title: "Angalia muunganisho wa intaneti",
    },
    network_error: {
      aria_description: "Jaribu kuchanganua tena. Tatizo likiendelea, ghairi na ujaribu tena baadaye.",
      title: "Hitilafu ya mtandao",
    },
    retry_btn: "Jaribu tena",
    scanning_not_available: {
      aria_description: "Funga kisanduku hiki cha mazungumzo na ujaribu tena baadaye.",
      title: "Uchanganuzi haupatikani",
    },
    scanning_unsuccessful: {
      details: "Imeshindikana kugundua uso wako. Tafadhali jaribu tena.",
      title: "Uchanganuzi haukufaulu",
    },
  },
  feedback_messages: {
    angled_pitch: "Tazama moja kwa moja kwenye kamera",
    angled_roll: "Tazama moja kwa moja kwenye kamera",
    angled_yaw: "Tazama moja kwa moja kwenye kamera",
    capture_complete_aria: "Imefaulu! Uso umenaswa",
    face_not_found: "Weka uso wako katikati ya skrini",
    multiple_faces: "Uso mmoja tu unapaswa kuonekana",
    not_still: "Usisonge",
    ok: "Sawa kabisa! Usisonge",
    too_blurry: "Usisonge",
    too_bright: "Nenda mahali penye mwanga usio mkali sana",
    too_close: "Songa mbali",
    too_close_to_border: "Weka uso wako katikati",
    too_dark: "Nenda mahali penye mwanga zaidi",
    too_far: "Songa karibu",
  },
  help_button: {
    aria_label: "Usaidizi",
    tooltip: "Unahitaji usaidizi?",
  },
  help_modal: {
    aria: "Msaada wa kunasa uso",
    back_btn: "Nyuma",
    done_btn: "Umemaliza",
    done_btn_aria: "Endelea kunasa uso",
    next_btn: "Endelea",
    steps: {
      camera_lens: {
        details: "Angalia kama lenzi ya kamera yako ina alama za vidole au vumbi. Lenzi chafu inaweza kufanya picha yako iwe na ukungu na kufanya iwe vigumu kwa mfumo kunasa uso wako kwa uwazi.",
        title: "Safisha lenzi ya kamera yako",
      },
      centered_face: {
        details: "Tazama moja kwa moja kwenye kamera na uweke uso wako katikati ya skrini. Shikilia kifaa chako bila kutikisika na uwe na mwonekano wa kawaida hadi uso wako unaswe.",
        title: "Weka uso wako katikati",
      },
      lighting: {
        details: "Hakikisha uso wako unaonekana wazi. Epuka mwanga hafifu sana au mkali sana, na elekea kwenye chanzo cha mwanga badala ya kuwa nacho nyuma yako.",
        title: "Tafuta mwanga mzuri",
      },
      obstructions: {
        details: "Hakikisha hakuna kinachofunika uso wako. Ondoa miwani ya jua, kofia au kitu chochote kinachofunika macho yako au sehemu za uso wako.",
        title: "Ondoa vizuizi",
      },
    },
  },
  onboarding_modal: {
    aria: "Maelekezo ya kunasa uso",
    cancel_btn: "Ghairi",
    details: "Hakikisha umetulia na umeweka uso wako katikati ya skrini ya kamera.",
    start_btn: "Anza kuskani",
    title: "Tazama moja kwa moja kwenye kamera",
  },
  processing: "Inachakata...",
  sdk_aria: "Nasa uso wako",
} as const;
