/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for tr. Generated by core-i18n. */
export default {
  close: "Kapat",
  error_dialogs: {
    cancel_btn: "Taramayı iptal et",
    check_internet_connection: {
      aria_description: "İnternete bağlanın, ardından taramayı yeniden deneyin.",
      title: "İnternet bağlantısını kontrol edin",
    },
    network_error: {
      aria_description: "Taramayı yeniden deneyin. Sorun devam ederse iptal edin ve daha sonra tekrar deneyin.",
      title: "Ağ hatası",
    },
    retry_btn: "Tekrar dene",
    scanning_not_available: {
      aria_description: "Bu iletişim kutusunu kapatın ve daha sonra tekrar deneyin.",
      title: "Tarama yapılamıyor",
    },
    scanning_unsuccessful: {
      details: "Yüzünüz algılanamadı. Lütfen tekrar deneyin.",
      title: "Tarama başarısız oldu",
    },
  },
  feedback_messages: {
    angled_pitch: "Doğrudan kameraya bakın",
    angled_roll: "Doğrudan kameraya bakın",
    angled_yaw: "Doğrudan kameraya bakın",
    capture_complete_aria: "Başarılı! Yüzünüz yakalandı",
    face_not_found: "Yüzünüzü ekranda ortalayın",
    multiple_faces: "Yalnızca bir yüz görünmelidir",
    not_still: "Hareketsiz durun",
    ok: "Mükemmel! Hareketsiz durun",
    too_blurry: "Hareketsiz durun",
    too_bright: "Daha yumuşak ışıklı bir yere geçin",
    too_close: "Uzaklaş",
    too_close_to_border: "Yüzünüzü ortalayın",
    too_dark: "Daha aydınlık bir yere geçin",
    too_far: "Yaklaş",
  },
  help_button: {
    aria_label: "Yardım",
    tooltip: "Yardıma mı ihtiyacın var?",
  },
  help_modal: {
    aria: "Yüz yakalama yardımı",
    back_btn: "Geri",
    done_btn: "Bitti",
    done_btn_aria: "Yüz yakalamaya devam edin",
    next_btn: "Sonraki",
    steps: {
      camera_lens: {
        details: "Kameranızın lensinde leke veya toz olup olmadığını kontrol edin. Kirli bir lens fotoğrafınızı bulanıklaştırabilir ve sistemin yüzünüzü net şekilde yakalamasını zorlaştırabilir.",
        title: "Kamera lenslerinizi temizleyin",
      },
      centered_face: {
        details: "Doğrudan kameraya bakın ve yüzünüzü ekranda ortalayın. Cihazınızı sabit tutun ve yüzünüz yakalanana kadar ifadenizi nötr tutun.",
        title: "Yüzünüzü ortada tutun",
      },
      lighting: {
        details: "Yüzünüzün net şekilde göründüğünden emin olun. Çok karanlık veya çok parlak ışıktan kaçının. Işık kaynağını arkanıza almayın; ışığa dönük durun.",
        title: "İyi aydınlatılmış bir yer bulun",
      },
      obstructions: {
        details: "Yüzünüzü hiçbir şeyin kapatmadığından emin olun. Gözlerinizi veya yüz hatlarınızı kapatan güneş gözlüğünü, şapkayı ya da diğer nesneleri çıkarın.",
        title: "Engelleri kaldırın",
      },
    },
  },
  onboarding_modal: {
    aria: "Yüz yakalama talimatları",
    cancel_btn: "İptal",
    details: "Hareketsiz durun ve yüzünüzü kamera ekranında ortalayın.",
    start_btn: "Taramayı Başlat",
    title: "Doğrudan kameraya bakın",
  },
  processing: "İşleniyor...",
  sdk_aria: "Yüzünüzün görüntüsünü çekin",
} as const;
