/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for uz. Generated by core-i18n. */
export default {
  close: "Yopish",
  error_dialogs: {
    cancel_btn: "Skanerlashni bekor qilish",
    check_internet_connection: {
      aria_description: "Internetga ulang, so‘ngra skanerlashni qayta urinib ko‘ring.",
      title: "Internet ulanishini tekshiring",
    },
    network_error: {
      aria_description: "Skanerlashni qayta urinib ko‘ring. Muammo davom etsa, bekor qiling va keyinroq yana urinib ko‘ring.",
      title: "Tarmoq xatosi",
    },
    retry_btn: "Qayta urining",
    scanning_not_available: {
      aria_description: "Ushbu oynani yoping va keyinroq yana urinib ko‘ring.",
      title: "Skanerlash mavjud emas",
    },
    scanning_unsuccessful: {
      details: "Yuzingiz aniqlanmadi. Qayta urinib ko‘ring.",
      title: "Skanerlash muvaffaqiyatsiz tugadi",
    },
  },
  feedback_messages: {
    angled_pitch: "Kameraga tik qarang",
    angled_roll: "Kameraga tik qarang",
    angled_yaw: "Kameraga tik qarang",
    capture_complete_aria: "Muvaffaqiyatli! Yuz tasvirga olindi",
    face_not_found: "Yuzingizni ekranning markaziga joylashtiring",
    multiple_faces: "Faqat bitta yuz ko‘rinishi kerak",
    not_still: "Qimirlamang",
    ok: "Ajoyib! Qimirlamang",
    too_blurry: "Qimirlamang",
    too_bright: "Yorug‘ligi yumshoqroq joyga o‘ting",
    too_close: "Uzoqlashtiring",
    too_close_to_border: "Yuzingizni markazga joylashtiring",
    too_dark: "Yorug‘roq joyga o‘ting",
    too_far: "Yaqinlashtiring",
  },
  help_button: {
    aria_label: "Yordam",
    tooltip: "Yordam kerakmi?",
  },
  help_modal: {
    aria: "Yuzni tasvirga olish bo‘yicha yordam",
    back_btn: "Ortga",
    done_btn: "Tayyor",
    done_btn_aria: "Yuzni tasvirga olishni davom ettirish",
    next_btn: "Keyingisi",
    steps: {
      camera_lens: {
        details: "Kamera linzasida dog‘ yoki chang borligini tekshiring. Kir linza suratingizni xiralashtirishi va tizimning yuzingizni aniq tasvirga olishini qiyinlashtirishi mumkin.",
        title: "Kamerangiz obyektivini tozalang",
      },
      centered_face: {
        details: "Kameraga to‘g‘ri qarang va yuzingizni ekranning markaziga joylashtiring. Qurilmangizni qimirlatmay ushlang va yuzingiz tasvirga olinguncha yuz ifodangizni neytral saqlang.",
        title: "Yuzingizni markazda tuting",
      },
      lighting: {
        details: "Yuzingiz aniq ko‘rinayotganiga ishonch hosil qiling. Juda qorong‘i yoki juda yorug‘ joylardan saqlaning va yorug‘lik manbai orqangizda bo‘lmasin, yorug‘lik yuzingizga tushsin.",
        title: "Yaxshi yoritilgan joyni toping",
      },
      obstructions: {
        details: "Yuzingizni hech narsa to‘sib turmaganiga ishonch hosil qiling. Ko‘zlaringizni yoki yuzingizning boshqa qismlarini to‘sadigan quyosh ko‘zoynagini, bosh kiyimni yoki boshqa narsalarni olib tashlang.",
        title: "To‘siqlarni olib tashlang",
      },
    },
  },
  onboarding_modal: {
    aria: "Yuzni tasvirga olish bo‘yicha ko‘rsatmalar",
    cancel_btn: "Bekor qilish",
    details: "Qimirlamang va yuzingizni kamera ekranining markaziga joylashtiring.",
    start_btn: "Skanerlashni boshlash",
    title: "Kameraga tik qarang",
  },
  processing: "Qayta ishlanmoqda...",
  sdk_aria: "Yuzingizni tasvirga oling",
} as const;
