/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for vi. Generated by core-i18n. */
export default {
  close: "Đóng",
  error_dialogs: {
    cancel_btn: "Hủy quét",
    check_internet_connection: {
      aria_description: "Kết nối Internet, rồi thử quét lại.",
      title: "Kiểm tra kết nối Internet",
    },
    network_error: {
      aria_description: "Thử quét lại. Nếu sự cố vẫn tiếp diễn, hãy hủy và thử lại sau.",
      title: "Lỗi mạng",
    },
    retry_btn: "Thử lại",
    scanning_not_available: {
      aria_description: "Đóng hộp thoại này và thử lại sau.",
      title: "Không thể quét",
    },
    scanning_unsuccessful: {
      details: "Không thể phát hiện khuôn mặt của bạn. Vui lòng thử lại.",
      title: "Quét không thành công",
    },
  },
  feedback_messages: {
    angled_pitch: "Nhìn thẳng vào camera",
    angled_roll: "Nhìn thẳng vào camera",
    angled_yaw: "Nhìn thẳng vào camera",
    capture_complete_aria: "Thành công! Đã chụp khuôn mặt",
    face_not_found: "Đặt khuôn mặt của bạn vào giữa màn hình",
    multiple_faces: "Chỉ để một khuôn mặt trong khung hình",
    not_still: "Giữ yên",
    ok: "Hoàn hảo! Giữ yên",
    too_blurry: "Giữ yên",
    too_bright: "Di chuyển đến nơi có ánh sáng dịu hơn",
    too_close: "Di chuyển xa hơn",
    too_close_to_border: "Đưa khuôn mặt vào giữa",
    too_dark: "Di chuyển đến nơi sáng hơn",
    too_far: "Di chuyển gần hơn",
  },
  help_button: {
    aria_label: "Trợ giúp",
    tooltip: "Bạn cần trợ giúp?",
  },
  help_modal: {
    aria: "Trợ giúp chụp khuôn mặt",
    back_btn: "Quay lại",
    done_btn: "Đã xong",
    done_btn_aria: "Tiếp tục chụp khuôn mặt",
    next_btn: "Tiếp theo",
    steps: {
      camera_lens: {
        details: "Kiểm tra ống kính máy ảnh xem có vết bẩn hoặc bụi không. Ống kính bẩn có thể làm ảnh bị mờ và khiến hệ thống khó chụp rõ khuôn mặt của bạn.",
        title: "Làm sạch ống kính camera",
      },
      centered_face: {
        details: "Nhìn thẳng vào máy ảnh và đặt khuôn mặt vào giữa màn hình. Giữ thiết bị ổn định và giữ nét mặt tự nhiên cho đến khi chụp được khuôn mặt.",
        title: "Giữ khuôn mặt ở giữa",
      },
      lighting: {
        details: "Đảm bảo khuôn mặt của bạn hiển thị rõ. Tránh ánh sáng quá tối hoặc quá chói, và hướng mặt về phía nguồn sáng thay vì để nguồn sáng ở phía sau.",
        title: "Tìm nơi có ánh sáng phù hợp",
      },
      obstructions: {
        details: "Đảm bảo không có gì che khuôn mặt của bạn. Tháo kính râm, mũ hoặc bất kỳ vật gì che mắt hay các nét trên khuôn mặt.",
        title: "Loại bỏ vật che khuất",
      },
    },
  },
  onboarding_modal: {
    aria: "Hướng dẫn chụp khuôn mặt",
    cancel_btn: "Hủy",
    details: "Giữ yên và căn giữa khuôn mặt trong khung hình camera.",
    start_btn: "Bắt đầu quét",
    title: "Nhìn thẳng vào camera",
  },
  processing: "Đang xử lý...",
  sdk_aria: "Chụp khuôn mặt",
} as const;
