/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for yo. Generated by core-i18n. */
export default {
  close: "Pàdé",
  error_dialogs: {
    cancel_btn: "Fagilé ìṣàyẹ̀wò",
    check_internet_connection: {
      aria_description: "Sopọ̀ mọ́ íńtánẹ́ẹ̀tì, lẹ́yìn náà tun ìṣàyẹ̀wò ṣe.",
      title: "Ṣàyẹ̀wò ìsopọ̀ íńtánẹ́ẹ̀tì",
    },
    network_error: {
      aria_description: "Tun ìṣàyẹ̀wò ṣe. Tí ìṣòro náà bá tẹ̀síwájú, fagilé ìṣàyẹ̀wò náà, kí o sì tún gbìyànjú nígbà mìíràn.",
      title: "Àṣìṣe nẹ́tíwọ́ọ̀kì",
    },
    retry_btn: "Tún gbìyànjú síi",
    scanning_not_available: {
      aria_description: "Tì àpótí ìjíròrò yìí pa, kí o sì tún gbìyànjú nígbà mìíràn.",
      title: "Ìṣàyẹ̀wò kò sí lárọwọ́tó",
    },
    scanning_unsuccessful: {
      details: "A kò lè rí ojú rẹ. Jọ̀wọ́, tún gbìyànjú.",
      title: "Ìṣàyẹ̀wò kò yọrí sí rere",
    },
  },
  feedback_messages: {
    angled_pitch: "Wo tààrà sí inú kámẹ́rà",
    angled_roll: "Wo tààrà sí inú kámẹ́rà",
    angled_yaw: "Wo tààrà sí inú kámẹ́rà",
    capture_complete_aria: "Àṣeyọrí! A ti mú ojú rẹ",
    face_not_found: "Gbe ojú rẹ sí àárín iboju",
    multiple_faces: "Jẹ́ kí ojú kan ṣoṣo hàn",
    not_still: "Dúró jẹ́ẹ́",
    ok: "Ó dáa! Dúró jẹ́ẹ́",
    too_blurry: "Dúró jẹ́ẹ́",
    too_bright: "Gbe lọ sí ibi tí ìmọ́lẹ̀ kò le gan",
    too_close: "Sún jìnnà síi",
    too_close_to_border: "Gbe ojú rẹ sí àárín",
    too_dark: "Gbe lọ sí ibi tí ìmọ́lẹ̀ pọ̀ síi",
    too_far: "Sún mọ́ síi",
  },
  help_button: {
    aria_label: "Ìrànlọ́wọ́",
    tooltip: "Ṣé o nílò ìrànlọ́wọ́?",
  },
  help_modal: {
    aria: "Ìrànlọ́wọ́ fún mímú ojú",
    back_btn: "Padà",
    done_btn: "Parí",
    done_btn_aria: "Tẹ̀síwájú nínú yíyà ojú rẹ",
    next_btn: "Tó kàn",
    steps: {
      camera_lens: {
        details: "Ṣàyẹ̀wò lẹ́ẹ̀nsi káàmárà rẹ fún àbàwọ́n tàbí erùpẹ̀. Lẹ́ẹ̀nsi tí ó dọ̀tí lè mú kí àwòrán rẹ dàrú, kí ó sì mú kó ṣòro fún ẹ̀rọ náà láti mú ojú rẹ ní kedere.",
        title: "Nu awò ojú kámẹ́rà rẹ nù",
      },
      centered_face: {
        details: "Wo káàmárà náà tààrà, kí o sì gbe ojú rẹ sí àárín iboju. Di ẹ̀rọ rẹ mú ṣinṣin, kí o sì jẹ́ kí ojú rẹ dúró láìfi ìmọ̀lára hàn títí a ó fi mú un.",
        title: "Jẹ́ kí ojú rẹ wà ní àárín",
      },
      lighting: {
        details: "Rí i dájú pé ojú rẹ hàn ní kedere. Yẹra fún ìmọ́lẹ̀ tí ó ṣókùnkùn gan tàbí tí ó le gan, kí o sì dojú kọ orísun ìmọ́lẹ̀ dípò kí ó wà lẹ́yìn rẹ.",
        title: "Wá ìmọ́lẹ̀ tó dáa",
      },
      obstructions: {
        details: "Rí i dájú pé kò sí ohun tí ó bo ojú rẹ. Yọ gíláàsì oòrùn, fìlà, tàbí ohunkóhun tí ó bo ojú tàbí àwọn ẹ̀yà ojú rẹ.",
        title: "Yọ àwọn ohun tí ó dí ojú",
      },
    },
  },
  onboarding_modal: {
    aria: "Àwọn ìtọ́nisọ́nà fún yíyà ojú",
    cancel_btn: "Fagilee",
    details: "Rí i dájú pé o dúró jẹ́ẹ́, kí o sì fi ojú rẹ sí àárín ìbojú kámẹ́rà.",
    start_btn: "Bẹ̀rẹ̀ ṣíṣẹ́dà àwòrán",
    title: "Wo tààrà sí inú kámẹ́rà",
  },
  processing: "Ń ṣiṣẹ́ lórí rẹ̀...",
  sdk_aria: "Ya àwòrán ojú rẹ",
} as const;
