/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for zh_CN. Generated by core-i18n. */
export default {
  close: "关闭",
  error_dialogs: {
    cancel_btn: "取消扫描",
    check_internet_connection: {
      aria_description: "请连接互联网，然后重试扫描。",
      title: "检查网络连接",
    },
    network_error: {
      aria_description: "重试扫描。如果问题仍然存在，请取消并稍后重试。",
      title: "网络错误",
    },
    retry_btn: "重试",
    scanning_not_available: {
      aria_description: "关闭此对话框，然后稍后重试。",
      title: "无法扫描",
    },
    scanning_unsuccessful: {
      details: "未检测到您的面部。请重试。",
      title: "扫描未成功",
    },
  },
  feedback_messages: {
    angled_pitch: "请正对相机",
    angled_roll: "请正对相机",
    angled_yaw: "请正对相机",
    capture_complete_aria: "成功！已捕获面部",
    face_not_found: "将面部置于屏幕中央",
    multiple_faces: "确保画面中只有一张脸",
    not_still: "保持不动",
    ok: "位置合适！请保持不动",
    too_blurry: "保持不动",
    too_bright: "移至光线较柔和的位置",
    too_close: "离远一些",
    too_close_to_border: "将面部置于中央",
    too_dark: "移至光线更充足的位置",
    too_far: "靠近一些",
  },
  help_button: {
    aria_label: "帮助",
    tooltip: "需要帮助？",
  },
  help_modal: {
    aria: "面部捕获帮助",
    back_btn: "返回",
    done_btn: "完成",
    done_btn_aria: "继续人脸采集",
    next_btn: "下一步",
    steps: {
      camera_lens: {
        details: "检查相机镜头是否有污渍或灰尘。镜头脏污会使照片模糊，导致系统难以清晰捕获您的面部。",
        title: "清洁摄像头镜头",
      },
      centered_face: {
        details: "正视相机，将面部置于屏幕中央。保持设备稳定并保持自然表情，直到捕获到您的面部。",
        title: "保持面部居中",
      },
      lighting: {
        details: "确保面部清晰可见。避免光线过暗或过亮，并面向光源，避免背对光源。",
        title: "选择合适的光线",
      },
      obstructions: {
        details: "确保没有物体遮挡面部。请取下墨镜、帽子或其他遮挡眼睛或面部特征的物品。",
        title: "移除遮挡物",
      },
    },
  },
  onboarding_modal: {
    aria: "人脸采集说明",
    cancel_btn: "取消",
    details: "请保持静止，并将人脸置于相机画面中央。",
    start_btn: "开始扫描",
    title: "请正对相机",
  },
  processing: "正在处理…",
  sdk_aria: "采集人脸",
} as const;
