/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for zh_TW. Generated by core-i18n. */
export default {
  close: "關閉",
  error_dialogs: {
    cancel_btn: "取消掃描",
    check_internet_connection: {
      aria_description: "請連線至網際網路，然後重試掃描。",
      title: "檢查網際網路連線",
    },
    network_error: {
      aria_description: "重試掃描。如果問題持續發生，請取消並稍後再試。",
      title: "網路錯誤",
    },
    retry_btn: "重試",
    scanning_not_available: {
      aria_description: "關閉此對話方塊，稍後再試。",
      title: "目前無法掃描",
    },
    scanning_unsuccessful: {
      details: "無法偵測到您的臉部。請再試一次。",
      title: "掃描未成功",
    },
  },
  feedback_messages: {
    angled_pitch: "請直視相機",
    angled_roll: "請直視相機",
    angled_yaw: "請直視相機",
    capture_complete_aria: "成功！臉部擷取完成",
    face_not_found: "將臉部置於畫面中央",
    multiple_faces: "畫面中只能有一張臉",
    not_still: "請保持不動",
    ok: "位置正確！請保持不動",
    too_blurry: "請保持不動",
    too_bright: "移至光線較柔和的位置",
    too_close: "再離遠一點",
    too_close_to_border: "將臉部置中",
    too_dark: "移至較明亮的位置",
    too_far: "再靠近一點",
  },
  help_button: {
    aria_label: "說明",
    tooltip: "需要協助嗎？",
  },
  help_modal: {
    aria: "臉部擷取說明",
    back_btn: "背面",
    done_btn: "完成",
    done_btn_aria: "繼續擷取臉部",
    next_btn: "下一步",
    steps: {
      camera_lens: {
        details: "檢查相機鏡頭是否有污漬或灰塵。髒污的鏡頭可能會讓影像模糊，使系統難以清楚擷取您的臉部。",
        title: "清潔相機鏡頭",
      },
      centered_face: {
        details: "直視相機，並將臉部置於畫面中央。穩住裝置並保持自然表情，直到擷取到您的臉部。",
        title: "讓臉部保持置中",
      },
      lighting: {
        details: "請確認臉部清晰可見。避免過暗或過亮的光線，並面向光源，避免讓光源位於身後。",
        title: "尋找合適的光線",
      },
      obstructions: {
        details: "請確認沒有任何物品遮住臉部。取下太陽眼鏡、帽子或任何遮擋眼睛或臉部特徵的物品。",
        title: "移除遮擋物",
      },
    },
  },
  onboarding_modal: {
    aria: "臉部擷取說明",
    cancel_btn: "取消",
    details: "請保持不動，並將臉部置於相機畫面中央。",
    start_btn: "開始掃描",
    title: "請直視相機",
  },
  processing: "處理中…",
  sdk_aria: "擷取您的臉部",
} as const;
