/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for fa-latn. Generated by core-i18n. */
export default {
  feedback_messages: {
    blur_detected: "Kart va telefon râ bi-harekat negah dârid",
    blur_detected_desktop: "Kart va dastgâh râ bi-harekat negah dârid",
    camera_angle_too_steep: "Kart ra movazi ba telefon negah darid",
    camera_angle_too_steep_desktop: "Kart ra movazi ba namayeshgar negah darid",
    card_number_scanned: "Samte shomâre-ye kart bâ movaffaghiyat eskan shod",
    card_scanned: "Kart bâ movaffaghiyat eskan shod",
    document_too_close_to_edge: "Door-tar beravid",
    flip_card: "Kart ra varune konid",
    flip_to_back_side: "Kart ra varune konid",
    move_closer: "Nazdik-tar biyayid",
    move_farther: "Door-tar beravid",
    occluded: "Kart ra kamelan namayan negah darid",
    scan_the_back_side: "Poshte kart ra eskan konid",
    scan_the_front_side: "Shomareye kart ra eskan konid",
  },
  flashlight_warning_message: "Havasetan be tabesh-e nur-e flash bashad.\nKart ra aheste jabeja konid ta tabesh az beyn beravad.",
  help_button: {
    aria_label: "Rahnama",
    tooltip: "Be rahnama niaz dârid?",
  },
  help_modal: {
    aria: "Rahnamay-e esken",
    back_btn: "Bazgasht",
    blur: {
      details: "Dar hengam-e eskan, telefon va kart ra bi-harekat negah darid. Harekat-e har kodam mitavanad tasvir ra tar konad va dadehaye kart ra nakhana konad.",
      details_desktop: "Dar hengam-e eskan, dastgah va kart ra bi-harekat negah darid. Harekat-e har kodam mitavanad tasvir ra tar konad va dadehaye kart ra nakhana konad.",
      title: "Hengam-e eskan bi-harekat bemanid",
    },
    camera_lens: {
      details: "Lenz-e dorbin ra az nazar-e lak ya gard-o-ghobar barresi konid. Lenz-e kasif tasvir-e nahayi ra tar mikonad, joz'iyat-e kart ra nakhana mikonad va az eskan-e movafagh-e dadeha jelogiri mikonad.",
      title: "Lenze dorbin ra tamiz konid",
    },
    card_number: {
      details: "Shomare kart ma'mulan 16 ragham darad, ama momken ast beyn-e 12 ta 19 ragham bashad. Bayad be surat-e chap-shode ya ba argham-e barjaste roye kart bashad. Momken ast dar ro ya posht-e kart gharar dashte bashad.",
      title: "Shomare kart kojast?",
    },
    done_btn: "Anjam shod",
    done_btn_aria: "Eskan ra edame dahid",
    lighting: {
      details: "Az nur-e mostaghim va shadid parhiz konid, zira az kart baztab mishavad va momken ast bakhshhayi az kart ra nakhana konad. Agar dadehaye kart ra nemitavanid bekhanid, dorbin ham natavanad anha ra bebinad.",
      title: "Movazeb nur-e shadid bashid",
    },
    next_btn: "Ba'di",
    occlusion: {
      details: "Hich bakhshi az kart, az jomle satrhaye payin, ra ba angosht napushanid. Moazebe baztabhaye hologram bashid ke ruye kadrhaye kart mioftand.",
      title: "Hameye kadrha ra namayan negah darid",
    },
  },
  onboarding_modal: {
    aria: "Rahnamaye eskan",
    btn: "Eskan râ shoru konid",
    details: "Shomare kart mamulan yek shomare 16-raghami ast. Bayad be surat-e chap-shode ya barjaste ruye kart bashad. Motma'en shavid ke kart khub roshan ast va hame-ye joziyat dida mishavand.",
    details_desktop: "Shomare kart mamulan yek shomare 16-raghami ast. Bayad be surat-e chap-shode ya barjaste ruye kart bashad. Motma'en shavid ke lens-e dowbinetan tamiz, kart khub roshan va hame-ye joziyat didani hastand.",
    title: "Aval shomare kart ra eskan konid",
  },
  sdk_aria: "Safhe-ye eskan-e kart",
  timeout_modal: {
    cancel_btn: "Esken ra laghv konid",
    details: "Motmaen shavid kart khub roshan, kamelan namayan va bedun-e tabesh ast.",
    details_desktop: "Motmaen shavid lenz-e dorbin tamiz ast va kart kamelan namayan, dar fokus va khub roshan ast.",
    retry_btn: "Dobâre talâsh konid",
    title: "Kart khande nashod",
  },
} as const;
