/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for sr. Generated by core-i18n. */
export default {
  feedback_messages: {
    blur_detected: "Držite karticu i telefon mirno",
    blur_detected_desktop: "Držite karticu i uređaj mirno",
    camera_angle_too_steep: "Držite karticu paralelno sa telefonom",
    camera_angle_too_steep_desktop: "Držite karticu paralelno sa ekranom",
    card_number_scanned: "Uspešno je skenirana strana kartice sa brojem kartice",
    card_scanned: "Kartica je uspešno skenirana",
    document_too_close_to_edge: "Udaljite se",
    flip_card: "Okrenite karticu",
    flip_to_back_side: "Okrenite karticu",
    move_closer: "Približite se",
    move_farther: "Udaljite se",
    occluded: "Neka kartica bude potpuno vidljiva",
    scan_the_back_side: "Skenirajte drugu stranu kartice",
    scan_the_front_side: "Skenirajte broj kartice",
  },
  flashlight_warning_message: "Pazite na odsjaj blica.\nNežno pomerajte karticu da biste ga izbegli.",
  help_button: {
    aria_label: "Pomoć",
    tooltip: "Treba vam pomoć?",
  },
  help_modal: {
    aria: "Pomoć za skeniranje",
    back_btn: "Nazad",
    blur: {
      details: "Pokušajte da držite telefon i karticu mirno tokom skeniranja. Pomeranje bilo kog od njih može zamutiti sliku i učiniti podatke na kartici nečitljivim.",
      details_desktop: "Pokušajte da držite uređaj i karticu mirno tokom skeniranja. Pomeranje bilo kog od njih može zamutiti sliku i učiniti podatke na kartici nečitljivim.",
      title: "Mirujte tokom skeniranja",
    },
    camera_lens: {
      details: "Proverite da li na objektivu kamere ima mrlja ili prašine. Prljav objektiv može zamutiti sliku, učiniti podatke na kartici nečitljivim i sprečiti uspešno skeniranje podataka.",
      title: "Očistite objektiv kamere",
    },
    card_number: {
      details: "Broj kartice obično ima 16 cifara, ali može imati od 12 do 19 cifara. Može biti odštampan ili utisnut reljefnim ciframa na kartici. Može se nalaziti na prednjoj ili zadnjoj strani kartice.",
      title: "Gde je broj kartice?",
    },
    done_btn: "Gotovo",
    done_btn_aria: "Nastavite skeniranje",
    lighting: {
      details: "Izbegavajte jaku direktnu svetlost jer se odbija od kartice i može učiniti delove kartice nečitljivim. Ako ne možete da pročitate podatke na kartici, neće biti vidljivi ni kameri.",
      title: "Pazite na jaku svetlost",
    },
    next_btn: "Dalje",
    occlusion: {
      details: "Uverite se da prstom ne prekrivate delove kartice, uključujući donje redove. Pazite i da odsjaj holograma ne prekriva polja na kartici.",
      title: "Neka sva polja budu vidljiva",
    },
  },
  onboarding_modal: {
    aria: "Uputstva za skeniranje",
    btn: "Započnite skeniranje",
    details: "Broj kartice obično ima 16 cifara. Može biti odštampan ili reljefno utisnut na kartici. Uverite se da je kartica dobro osvetljena i da su svi detalji vidljivi.",
    details_desktop: "Broj kartice obično ima 16 cifara. Može biti odštampan ili reljefno utisnut na kartici. Uverite se da je objektiv kamere čist, da je kartica dobro osvetljena i da su svi detalji vidljivi.",
    title: "Prvo skenirajte broj kartice",
  },
  sdk_aria: "Ekran za skeniranje kartice",
  timeout_modal: {
    cancel_btn: "Otkaži skeniranje",
    details: "Uverite se da je kartica dobro osvetljena, potpuno vidljiva i bez odsjaja.",
    details_desktop: "Uverite se da je objektiv kamere čist i da je kartica potpuno vidljiva, u fokusu i dobro osvetljena.",
    retry_btn: "Pokušajte ponovo",
    title: "Nije moguće očitati karticu",
  },
} as const;
