/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

import { defineConfig } from "oxlint";

const migratedErrorRules = [
  "no-empty-function",
  "no-var",
  "prefer-rest-params",
  "prefer-spread",
  "no-array-constructor",
  "no-loss-of-precision",
  "for-direction",
  "no-async-promise-executor",
  "no-case-declarations",
  "no-class-assign",
  "no-compare-neg-zero",
  "no-cond-assign",
  "no-constant-condition",
  "no-control-regex",
  "no-debugger",
  "no-delete-var",
  "no-dupe-else-if",
  "no-duplicate-case",
  "no-empty",
  "no-empty-character-class",
  "no-empty-pattern",
  "no-ex-assign",
  "no-extra-boolean-cast",
  "no-fallthrough",
  "no-global-assign",
  "no-inner-declarations",
  "no-invalid-regexp",
  "no-irregular-whitespace",
  "no-misleading-character-class",
  "no-nonoctal-decimal-escape",
  "no-prototype-builtins",
  "no-regex-spaces",
  "no-self-assign",
  "no-shadow-restricted-names",
  "no-sparse-arrays",
  "no-unsafe-finally",
  "no-unsafe-optional-chaining",
  "no-unused-labels",
  "no-useless-backreference",
  "no-useless-catch",
  "no-useless-escape",
  "no-with",
  "require-yield",
  "use-isnan",
  "valid-typeof",
  "typescript/adjacent-overload-signatures",
  "typescript/array-type",
  "typescript/ban-tslint-comment",
  "typescript/class-literal-property-style",
  "typescript/consistent-generic-constructors",
  "typescript/consistent-indexed-object-style",
  "typescript/consistent-type-assertions",
  "typescript/dot-notation",
  "typescript/no-confusing-non-null-assertion",
  "typescript/no-empty-interface",
  "typescript/no-inferrable-types",
  "typescript/non-nullable-type-assertion-style",
  "typescript/prefer-for-of",
  "typescript/prefer-function-type",
  "typescript/prefer-namespace-keyword",
  "typescript/prefer-string-starts-ends-with",
  "typescript/await-thenable",
  "typescript/ban-ts-comment",
  "typescript/ban-types",
  "typescript/no-duplicate-enum-values",
  "typescript/no-duplicate-type-constituents",
  "typescript/no-explicit-any",
  "typescript/no-extra-non-null-assertion",
  "typescript/no-floating-promises",
  "typescript/no-for-in-array",
  "typescript/no-implied-eval",
  "typescript/no-misused-new",
  "typescript/no-misused-promises",
  "typescript/no-namespace",
  "typescript/no-non-null-asserted-optional-chain",
  "typescript/no-redundant-type-constituents",
  "typescript/no-this-alias",
  "typescript/no-unnecessary-type-constraint",
  "typescript/no-unsafe-argument",
  "typescript/no-unsafe-call",
  "typescript/no-unsafe-declaration-merging",
  "typescript/no-unsafe-enum-comparison",
  "typescript/no-unsafe-return",
  "typescript/no-var-requires",
  "typescript/prefer-as-const",
  "typescript/require-await",
  "typescript/restrict-plus-operands",
  "typescript/restrict-template-expressions",
  "typescript/triple-slash-reference",
  "typescript/unbound-method",
] as const;

const migratedRules = Object.fromEntries(migratedErrorRules.map((rule) => [rule, "error"]));

const compatFiles = [
  "packages/blinkcard/src/**/*.{ts,tsx}",
  "packages/blinkcard-core/src/**/*.{ts,tsx}",
  "packages/blinkcard-ux-manager/src/**/*.{ts,tsx}",
  "packages/blinkcard-worker/src/**/*.{ts,tsx}",
  "packages/blinkid/src/**/*.{ts,tsx}",
  "packages/blinkid-core/src/**/*.{ts,tsx}",
  "packages/blinkid-ux-manager/src/**/*.{ts,tsx}",
  "packages/blinkid-worker/src/**/*.{ts,tsx}",
  "packages/blinkid-verify/src/**/*.{ts,tsx}",
  "packages/blinkid-verify-core/src/**/*.{ts,tsx}",
  "packages/blinkid-verify-ux-manager/src/**/*.{ts,tsx}",
  "packages/blinkid-verify-worker/src/**/*.{ts,tsx}",
  "packages/camera-manager/src/**/*.{ts,tsx}",
];

const solidRules = {
  "solid/jsx-no-duplicate-props": "error",
  "solid/jsx-no-undef": ["error", { typescriptEnabled: true }],
  "solid/jsx-uses-vars": "error",
  "solid/no-unknown-namespaces": "off",
  "solid/no-innerhtml": "error",
  "solid/jsx-no-script-url": "error",
  "solid/components-return-once": "warn",
  "solid/no-destructure": "error",
  "solid/prefer-for": "error",
  "solid/reactivity": "warn",
  "solid/event-handlers": "warn",
  "solid/imports": "warn",
  "solid/style-prop": "warn",
  "solid/no-react-deps": "warn",
  "solid/no-react-specific-props": "warn",
  "solid/self-closing-comp": "warn",
  "solid/no-array-handlers": "off",
  "solid/prefer-show": "off",
  "solid/no-proxy-apis": "off",
  "solid/prefer-classlist": "off",
} as const;

export default defineConfig({
  plugins: ["typescript", "unicorn"],
  ignorePatterns: [
    "**/CHANGELOG.md",
    "LICENCE_NOTICE.md",
    "pnpm-lock.yaml",
    "localization.lock.json",
    "**/src/ui/locales/**",
    "node_modules",
    ".idea/**",
    ".turbo/**",
    ".pnpm-store/**",
    "**/dist/**",
    "**/.output/**",
  ],
  jsPlugins: [
    "eslint-plugin-compat",
    "eslint-plugin-solid",
    "oxlint-plugin-oxfmt",
    {
      name: "stylistic",
      specifier: "@stylistic/eslint-plugin",
    },
  ],
  categories: {
    correctness: "off",
  },
  options: {
    typeAware: true,
  },
  env: {
    builtin: true,
    browser: true,
    node: true,
    worker: true,
  },
  rules: {
    "oxfmt/format": "error",
  },
  overrides: [
    {
      files: ["**/*.{ts,tsx}"],
      rules: { ...migratedRules, ...solidRules },
    },
    {
      files: compatFiles,
      rules: {
        "compat/compat": "error",
      },
    },
  ],
});
