/**
 * Copyright (c) 2026 Microblink Ltd. All rights reserved.
 */

/*
 * This file is auto-generated by a script.
 * DO NOT EDIT MANUALLY.
 */

import type { PingBrowserDeviceInfo } from "./ping.browser.device.info";
import type { PingError } from "./ping.error";
import type { PingCameraHardwareInfo } from "./ping.hardware.camera.info";
import type { PingLog } from "./ping.log";
import type { PingCameraInputInfo } from "./ping.sdk.camera.input.info";
import type { PingCameraPermission } from "./ping.sdk.camera.permission";
import type { PingSdkInitStart } from "./ping.sdk.init.start";
import type { PingScanningConditions } from "./ping.sdk.scan.conditions";
import type { PingUxEvent } from "./ping.sdk.ux.event";
import type { PingWrapperProductInfo } from "./ping.sdk.wrapper.product";

export type Ping =
  | PingBrowserDeviceInfo
  | PingError
  | PingCameraHardwareInfo
  | PingLog
  | PingCameraInputInfo
  | PingCameraPermission
  | PingSdkInitStart
  | PingScanningConditions
  | PingUxEvent
  | PingWrapperProductInfo;

export type SchemaName = Ping["schemaName"];
