/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ak. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Twa mu",
  camera_error_details: "Yɛsrɛw ma kamɛra ho kwan wɔ wo brawsa mu na yɛ bio.",
  camera_error_primary_btn: "San yɛ bio",
  camera_error_title: "Wuhia kamɛra hokwan",
  close: "Tum",
  dialog_title: "Skaane krataa bi",
  loading_cameras: "Ɛde kamɛra ahorow regu so...",
  mirror_camera: "Yɛ mfoninitwa afiri no sɛ ahwehwɛ",
  select_a_camera: "Paw mfoninitwa afiri bi",
  select_camera: "Paw mfoninitwa afiri",
  selected_camera: "Mfoninitwa afiri a woapaw",
  torch: "Kanea",
} as const;
