/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for am. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "ሰርዝ",
  camera_error_details: "እባክዎ በአሳሽዎ ውስጥ የካሜራ መዳረሻ ይፍቀዱና እንደገና ይሞክሩ።",
  camera_error_primary_btn: "እንደገና ይሞክሩ",
  camera_error_title: "የካሜራ ፈቃድ ያስፈልጋል",
  close: "ዝጋ",
  dialog_title: "ሰነድ ይቃኙ",
  loading_cameras: "ካሜራዎችን በመጫን ላይ...",
  mirror_camera: "የካሜራውን ምስል ይገልብጡ",
  select_a_camera: "ካሜራ ይምረጡ",
  select_camera: "ካሜራ ይምረጡ",
  selected_camera: "የተመረጠ ካሜራ",
  torch: "ፍላሽ",
} as const;
