/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ar. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "إلغاء",
  camera_error_details: "يُرجى السماح بالوصول إلى الكاميرا في متصفحك ثم المحاولة مرة أخرى.",
  camera_error_primary_btn: "إعادة المحاولة",
  camera_error_title: "مطلوب إذن الكاميرا",
  close: "إغلاق",
  dialog_title: "مسح مستند ضوئيًا",
  loading_cameras: "جارٍ تحميل الكاميرات...",
  mirror_camera: "عكس صورة الكاميرا",
  select_a_camera: "اختر كاميرا",
  select_camera: "اختر الكاميرا",
  selected_camera: "الكاميرا المحددة",
  torch: "المصباح",
} as const;
