/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for bn. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "বাতিল করুন",
  camera_error_details: "অনুগ্রহ করে আপনার ব্রাউজারে ক্যামেরা অ্যাক্সেসের অনুমতি দিন এবং আবার চেষ্টা করুন।",
  camera_error_primary_btn: "পুনরায় চেষ্টা করুন",
  camera_error_title: "ক্যামেরা অনুমতি প্রয়োজন",
  close: "বন্ধ করুন",
  dialog_title: "একটি ডকুমেন্ট স্ক্যান করুন",
  loading_cameras: "ক্যামেরা লোড হচ্ছে...",
  mirror_camera: "ক্যামেরার দৃশ্য উল্টান",
  select_a_camera: "একটি ক্যামেরা নির্বাচন করুন",
  select_camera: "ক্যামেরা নির্বাচন করুন",
  selected_camera: "নির্বাচিত ক্যামেরা",
  torch: "ফ্ল্যাশলাইট",
} as const;
