/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for cs. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Zrušit",
  camera_error_details: "Povolte v prohlížeči přístup k fotoaparátu a zkuste to znovu.",
  camera_error_primary_btn: "Opakovat",
  camera_error_title: "Je vyžadováno oprávnění pro fotoaparát",
  close: "Zavřít",
  dialog_title: "Naskenovat dokument",
  loading_cameras: "Načítají se fotoaparáty…",
  mirror_camera: "Zrcadlově převrátit obraz kamery",
  select_a_camera: "Vyberte kameru",
  select_camera: "Vybrat kameru",
  selected_camera: "Vybraná kamera",
  torch: "Svítilna",
} as const;
