/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for el. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Ακύρωση",
  camera_error_details: "Επιτρέψτε την πρόσβαση στην κάμερα στο πρόγραμμα περιήγησ΄ής σας και δοκιμάστε ξανά.",
  camera_error_primary_btn: "Επανάληψη",
  camera_error_title: "Απαιτείται η άδεια της κάμερας",
  close: "Κλείσιμο",
  dialog_title: "Σαρώστε ένα έγγραφο",
  loading_cameras: "Φόρτωση καμερών σε εξέλιξη...",
  mirror_camera: "Κατοπτρισμός κάμερας",
  select_a_camera: "Επιλέξτε κάμερα",
  select_camera: "Επιλέξτε κάμερα",
  selected_camera: "Επιλεγμένη κάμερα",
  torch: "Φακός",
} as const;
