/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for fa-latn. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Laghv",
  camera_error_details: "لطفاً دسترسی دوربین را در مرورگر خود فعال کنید و دوباره امتحان کنید.",
  camera_error_primary_btn: "دوباره امتحان کنید",
  camera_error_title: "مجوز دوربین لازم است",
  close: "بستن",
  dialog_title: "اسکن یک سند",
  loading_cameras: "در حال بارگذاری دوربین‌ها...",
  mirror_camera: "Tasvir-e dorbîn râ âyene'i konid",
  select_a_camera: "Yek dorbîn entekhâb konid",
  select_camera: "Dorbîn râ entekhâb konid",
  selected_camera: "Dorbîn-e entekhâb-shode",
  torch: "Cherâgh-qovve",
} as const;
