/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for fi. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Peruuta",
  camera_error_details: "Anna kameran käyttöoikeus selaimessasi ja yritä uudelleen.",
  camera_error_primary_btn: "Yritä uudelleen",
  camera_error_title: "Kameran käyttöoikeus tarvitaan",
  close: "Sulje",
  dialog_title: "Skannaa asiakirja",
  loading_cameras: "Ladataan kameroita...",
  mirror_camera: "Peilaa kamerakuva",
  select_a_camera: "Valitse kamera",
  select_camera: "Valitse kamera",
  selected_camera: "Valittu kamera",
  torch: "Taskulamppu",
} as const;
