/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for fil. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Kanselahin",
  camera_error_details: "Pakipayagan ang access sa camera sa browser mo at subukan ulit.",
  camera_error_primary_btn: "Subukan ulit",
  camera_error_title: "Kailangan ng pahintulot sa camera",
  close: "Isara",
  dialog_title: "I-scan ang dokumento",
  loading_cameras: "Inilo-load ang mga camera...",
  mirror_camera: "I-mirror ang camera",
  select_a_camera: "Pumili ng camera",
  select_camera: "Pumili ng camera",
  selected_camera: "Napiling camera",
  torch: "Flash",
} as const;
