/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for fr_CA. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Annuler",
  camera_error_details: "Veuillez autoriser l'accès à la caméra dans votre navigateur et réessayer.",
  camera_error_primary_btn: "Réessayer",
  camera_error_title: "Autorisation d'accès à la caméra requise",
  close: "Fermer",
  dialog_title: "Numériser un document",
  loading_cameras: "Chargement des caméras...",
  mirror_camera: "Inverser l’image de la caméra",
  select_a_camera: "Sélectionnez une caméra",
  select_camera: "Sélectionner la caméra",
  selected_camera: "Caméra sélectionnée",
  torch: "Lampe torche",
} as const;
