/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ha. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Soke",
  camera_error_details: "A ba wa kamara dama ta cikin burawuza sannan a sake gwadawa.",
  camera_error_primary_btn: "Sake gwadawa",
  camera_error_title: "Akwai buƙatar ba wa kamera izini",
  close: "Rufe",
  dialog_title: "A ɗauki hoton takarda",
  loading_cameras: "Ana buɗe kamarori...",
  mirror_camera: "Mayar da hoton kyamara kamar na madubi",
  select_a_camera: "Zaɓi kyamara",
  select_camera: "Zaɓi kyamara",
  selected_camera: "Kyamara da aka zaɓa",
  torch: "Fitilar kyamara",
} as const;
