/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for he. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "ביטול",
  camera_error_details: "נא לאפשר גישה למצלמה בדפדפן ולנסות שוב.",
  camera_error_primary_btn: "לנסות שוב",
  camera_error_title: "נדרשת הרשאת מצלמה",
  close: "סגור",
  dialog_title: "סריקת מסמך",
  loading_cameras: "טוען מצלמות...",
  mirror_camera: "שיקוף המצלמה",
  select_a_camera: "בחרו מצלמה",
  select_camera: "בחירת מצלמה",
  selected_camera: "המצלמה שנבחרה",
  torch: "פנס",
} as const;
