/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for hu. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Mégse",
  camera_error_details: "Kérjük, engedélyezze a kamera hozzáférését a böngészőjében, és próbálja újra.",
  camera_error_primary_btn: "Próbálja újra",
  camera_error_title: "Kamera engedélyezése szükséges",
  close: "Bezárás",
  dialog_title: "Dokumentum szkennelése",
  loading_cameras: "Kamerák betöltése...",
  mirror_camera: "Kamera tükrözése",
  select_a_camera: "Válasszon ki egy kamerát",
  select_camera: "Kamera kiválasztása",
  selected_camera: "Kiválasztott kamera",
  torch: "Zseblámpa",
} as const;
