/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for id. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Batal",
  camera_error_details: "Harap izinkan akses kamera di peramban dan coba lagi.",
  camera_error_primary_btn: "Coba Lagi",
  camera_error_title: "Perlu izin kamera",
  close: "Tutup",
  dialog_title: "Pindai dokumen",
  loading_cameras: "Memuat kamera...",
  mirror_camera: "Cerminkan kamera",
  select_a_camera: "Pilih kamera",
  select_camera: "Pilih kamera",
  selected_camera: "Kamera yang dipilih",
  torch: "Senter",
} as const;
