/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for is. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Hætta við",
  camera_error_details: "Leyfið myndavélaaðgang í vefskoðaranum og reynið aftur.",
  camera_error_primary_btn: "Reynið aftur",
  camera_error_title: "Heimild fyrir myndavél er nauðsynleg",
  close: "Loka",
  dialog_title: "Skanna skjal",
  loading_cameras: "Hleð myndavélum...",
  mirror_camera: "Spegla myndavélarmynd",
  select_a_camera: "Veldu myndavél",
  select_camera: "Veldu myndavél",
  selected_camera: "Valin myndavél",
  torch: "Vasaljós",
} as const;
