/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ka_GE. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "გაუქმება",
  camera_error_details: "დაუშვით კამერაზე წვდომა თქვენს ბრაუზერში და ხელახლა სცადეთ.",
  camera_error_primary_btn: "ხელახლა ცდა",
  camera_error_title: "საჭიროა კამერაზე წვდომა",
  close: "დახურვა",
  dialog_title: "დაასკანერეთ დოკუმენტი",
  loading_cameras: "მიმდინარეობს კამერების ჩატვირთვა...",
  mirror_camera: "კამერის გამოსახულების სარკისებურად ჩვენება",
  select_a_camera: "აირჩიეთ კამერა",
  select_camera: "კამერის არჩევა",
  selected_camera: "არჩეული კამერა",
  torch: "ფანარი",
} as const;
