/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ko. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "취소",
  camera_error_details: "브라우저에서 카메라의 접근을 허용하고 다시 시도해 주세요.",
  camera_error_primary_btn: "다시 시도",
  camera_error_title: "카메라 권한 필요",
  close: "닫기",
  dialog_title: "문서 스캔",
  loading_cameras: "카메라 불러오는 중...",
  mirror_camera: "카메라 미러링",
  select_a_camera: "카메라를 선택하세요",
  select_camera: "카메라 선택",
  selected_camera: "선택된 카메라",
  torch: "플래시",
} as const;
