/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for lv. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Atcelt",
  camera_error_details: "Pārlūkā atļaujiet piekļuvi kamerai un mēģiniet vēlreiz.",
  camera_error_primary_btn: "Mēģināt no jauna",
  camera_error_title: "Nepieciešama atļauja izmantot kameru",
  close: "Aizvērt",
  dialog_title: "Skenēt dokumentu",
  loading_cameras: "Ielādē kameras...",
  mirror_camera: "Spoguļot kameras attēlu",
  select_a_camera: "Atlasīt kameru",
  select_camera: "Atlasīt kameru",
  selected_camera: "Atlasītā kamera",
  torch: "Lukturītis",
} as const;
