/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ps_AF. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "لغوه کړئ",
  camera_error_details: "په مهربانۍ سره په خپل بروزر کې د کامرې لاسرسي اجازه ورکړئ او بیا هڅه وکړئ.",
  camera_error_primary_btn: "بیا هڅه وکړئ",
  camera_error_title: "کامرې ته د اجازې اړتیا ده",
  close: "تړل",
  dialog_title: "یو سند سکن کړئ",
  loading_cameras: "کامرې لوډ کېږي...",
  mirror_camera: "د کامرې انځور معکوس کړئ",
  select_a_camera: "یوه کامره وټاکئ",
  select_camera: "کامره وټاکئ",
  selected_camera: "ټاکل شوې کامره",
  torch: "فلش څراغ",
} as const;
