/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for pt. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Cancelar",
  camera_error_details: "Permita acesso à câmara no seu navegador e tente novamente.",
  camera_error_primary_btn: "Tente novamente",
  camera_error_title: "Necessário dar permissão à câmara",
  close: "Fechar",
  dialog_title: "Digitalizar um documento",
  loading_cameras: "A carregar câmaras...",
  mirror_camera: "Espelhar câmara",
  select_a_camera: "Selecione uma câmara",
  select_camera: "Selecionar câmara",
  selected_camera: "Câmara selecionada",
  torch: "Lanterna",
} as const;
