/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for pt_BR. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Cancelar",
  camera_error_details: "Permita o acesso à câmera no seu navegador e tente novamente.",
  camera_error_primary_btn: "Tentar novamente",
  camera_error_title: "Permissão da câmera necessária",
  close: "Fechar",
  dialog_title: "Escanear um documento",
  loading_cameras: "Carregando câmeras...",
  mirror_camera: "Espelhar câmera",
  select_a_camera: "Selecione uma câmera",
  select_camera: "Selecionar câmera",
  selected_camera: "Câmera selecionada",
  torch: "Lanterna",
} as const;
