/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for sl. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Prekliči",
  camera_error_details: "Dovolite dostop do kamere v brskalniku in poskusite znova.",
  camera_error_primary_btn: "Poskusi znova",
  camera_error_title: "Potrebno je dovoljenje za kamero",
  close: "Zapri",
  dialog_title: "Skenirajte dokument",
  loading_cameras: "Nalaganje kamer…",
  mirror_camera: "Zrcali kamero",
  select_a_camera: "Izberi kamero",
  select_camera: "Izberi kamero",
  selected_camera: "Izbrana kamera",
  torch: "Svetilka",
} as const;
