/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for sr. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Otkaži",
  camera_error_details: "Omogućite pristup kameri u pregledaču i pokušajte ponovo.",
  camera_error_primary_btn: "Pokušaj ponovo",
  camera_error_title: "Potrebna je dozvola za kameru",
  close: "Zatvori",
  dialog_title: "Skenirajte dokument",
  loading_cameras: "Učitavanje kamera…",
  mirror_camera: "Prikažite sliku kamere kao u ogledalu",
  select_a_camera: "Izaberite kameru",
  select_camera: "Izaberite kameru",
  selected_camera: "Izabrana kamera",
  torch: "Blic",
} as const;
