/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for tr. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "İptal",
  camera_error_details: "Lütfen tarayıcınızda kamera erişimine izin verin ve tekrar deneyin.",
  camera_error_primary_btn: "Tekrar dene",
  camera_error_title: "Kamera izni gerekli",
  close: "Kapat",
  dialog_title: "Bir belge tarayın",
  loading_cameras: "Kameralar yükleniyor...",
  mirror_camera: "Kamerayı yansıt",
  select_a_camera: "Bir kamera seçin",
  select_camera: "Kamerayı seçin",
  selected_camera: "Seçili kamera",
  torch: "Flaş",
} as const;
