/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for ur. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "منسوخ کریں",
  camera_error_details: "براؤزر میں کیمرہ کی اجازت دیں اور دوبارہ کوشش کریں۔",
  camera_error_primary_btn: "دوبارہ کوشش کریں",
  camera_error_title: "کیمرہ کی اجازت درکار ہے",
  close: "بند کریں",
  dialog_title: "ایک دستاویز اسکین کریں",
  loading_cameras: "کیمرے لوڈ ہو رہے ہیں...",
  mirror_camera: "کیمرے کی تصویر پلٹائیں",
  select_a_camera: "ایک کیمرا منتخب کریں",
  select_camera: "کیمرا منتخب کریں",
  selected_camera: "منتخب کردہ کیمرا",
  torch: "فلیش لائٹ",
} as const;
