/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for uz. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Bekor qilish",
  camera_error_details: "Brauzerda kamera ruxsatini bering va qayta urining.",
  camera_error_primary_btn: "Qayta urining",
  camera_error_title: "Kamera ruxsati zarur",
  close: "Yopish",
  dialog_title: "Hujjatni skanerlang",
  loading_cameras: "Kameralar yuklanmoqda...",
  mirror_camera: "Kamera tasvirini akslantirish",
  select_a_camera: "Kamerani tanlang",
  select_camera: "Kamerani tanlang",
  selected_camera: "Tanlangan kamera",
  torch: "Chiroq",
} as const;
