/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for vi. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "Hủy",
  camera_error_details: "Vui lòng cho phép truy cập máy ảnh trên trình duyệt của bạn và thử lại.",
  camera_error_primary_btn: "Thử lại",
  camera_error_title: "Cần phải cấp quyền truy cập máy ảnh",
  close: "Đóng",
  dialog_title: "Quét tài liệu",
  loading_cameras: "Đang tải máy ảnh...",
  mirror_camera: "Phản chiếu hình ảnh từ camera",
  select_a_camera: "Chọn một camera",
  select_camera: "Chọn camera",
  selected_camera: "Camera đã chọn",
  torch: "Đèn pin",
} as const;
