/** Copyright (c) 2026 Microblink Ltd. All rights reserved. */

/** Localization strings for zh_CN. Generated by core-i18n. */
export default {
  camera_error_cancel_btn: "取消",
  camera_error_details: "请在您的浏览器中允许相机访问权限,然后重试。",
  camera_error_primary_btn: "重试",
  camera_error_title: "需要相机许可",
  close: "关闭",
  dialog_title: "扫描文档",
  loading_cameras: "正在加载相机……",
  mirror_camera: "镜像摄像头",
  select_a_camera: "选择一个摄像头",
  select_camera: "选择摄像头",
  selected_camera: "已选择的摄像头",
  torch: "闪光灯",
} as const;
