/**
 * Copyright (c) 2026 Microblink Ltd. All rights reserved.
 */

/*
 * This file is auto-generated by a script.
 * DO NOT EDIT MANUALLY.
 */

import type { PingBrowserDeviceInfo } from "./ping.browser.device.info";
import type { PingError } from "./ping.error";
import type { PingHardwareCameraInfo } from "./ping.hardware.camera.info";
import type { PingLog } from "./ping.log";
import type { PingSdkCameraInputInfo } from "./ping.sdk.camera.input.info";
import type { PingSdkCameraPermission } from "./ping.sdk.camera.permission";
import type { PingSdkInitStart } from "./ping.sdk.init.start";
import type { PingSdkScanConditions } from "./ping.sdk.scan.conditions";
import type { PingSdkUxEvent } from "./ping.sdk.ux.event";
import type { PingSdkWrapperProduct } from "./ping.sdk.wrapper.product";

export type Ping =
  | PingBrowserDeviceInfo
  | PingError
  | PingHardwareCameraInfo
  | PingLog
  | PingSdkCameraInputInfo
  | PingSdkCameraPermission
  | PingSdkInitStart
  | PingSdkScanConditions
  | PingSdkUxEvent
  | PingSdkWrapperProduct;

export type SchemaName = Ping["schemaName"];
